// Code generated by ent, DO NOT EDIT.

package aicalllog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aicalllog type in the database.
	Label = "ai_call_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldSkill holds the string denoting the skill field in the database.
	FieldSkill = "skill"
	// FieldSnippetID holds the string denoting the snippet_id field in the database.
	FieldSnippetID = "snippet_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldPromptVersion holds the string denoting the prompt_version field in the database.
	FieldPromptVersion = "prompt_version"
	// FieldInputHash holds the string denoting the input_hash field in the database.
	FieldInputHash = "input_hash"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCachedTokens holds the string denoting the cached_tokens field in the database.
	FieldCachedTokens = "cached_tokens"
	// FieldCostUsd holds the string denoting the cost_usd field in the database.
	FieldCostUsd = "cost_usd"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the aicalllog in the database.
	Table = "ai_call_logs"
)

// Columns holds all SQL columns for aicalllog fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldSkill,
	FieldSnippetID,
	FieldProvider,
	FieldModel,
	FieldPromptVersion,
	FieldInputHash,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCachedTokens,
	FieldCostUsd,
	FieldLatencyMs,
	FieldStatus,
	FieldError,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SkillValidator is a validator for the "skill" field. It is called by the builders before save.
	SkillValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// PromptVersionValidator is a validator for the "prompt_version" field. It is called by the builders before save.
	PromptVersionValidator func(string) error
	// InputHashValidator is a validator for the "input_hash" field. It is called by the builders before save.
	InputHashValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultCachedTokens holds the default value on creation for the "cached_tokens" field.
	DefaultCachedTokens int
	// DefaultCostUsd holds the default value on creation for the "cost_usd" field.
	DefaultCostUsd float64
	// DefaultLatencyMs holds the default value on creation for the "latency_ms" field.
	DefaultLatencyMs int
	// ErrorValidator is a validator for the "error" field. It is called by the builders before save.
	ErrorValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusSuccess    Status = "success"
	StatusParseError Status = "parse_error"
	StatusLlmError   Status = "llm_error"
	StatusSkipped    Status = "skipped"
	StatusTimeout    Status = "timeout"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusParseError, StatusLlmError, StatusSkipped, StatusTimeout:
		return nil
	default:
		return fmt.Errorf("aicalllog: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AICallLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// BySkill orders the results by the skill field.
func BySkill(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkill, opts...).ToFunc()
}

// BySnippetID orders the results by the snippet_id field.
func BySnippetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnippetID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByPromptVersion orders the results by the prompt_version field.
func ByPromptVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptVersion, opts...).ToFunc()
}

// ByInputHash orders the results by the input_hash field.
func ByInputHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputHash, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCachedTokens orders the results by the cached_tokens field.
func ByCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedTokens, opts...).ToFunc()
}

// ByCostUsd orders the results by the cost_usd field.
func ByCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsd, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
