// Code generated by ent, DO NOT EDIT.

package paste

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/go-note/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldOwnerID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldTitle, v))
}

// ShortLink applies equality check predicate on the "short_link" field. It's identical to ShortLinkEQ.
func ShortLink(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldShortLink, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldContent, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldLanguage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int64) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int64) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int64) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldOwnerID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContainsFold(FieldTitle, v))
}

// ShortLinkEQ applies the EQ predicate on the "short_link" field.
func ShortLinkEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldShortLink, v))
}

// ShortLinkNEQ applies the NEQ predicate on the "short_link" field.
func ShortLinkNEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldShortLink, v))
}

// ShortLinkIn applies the In predicate on the "short_link" field.
func ShortLinkIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldShortLink, vs...))
}

// ShortLinkNotIn applies the NotIn predicate on the "short_link" field.
func ShortLinkNotIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldShortLink, vs...))
}

// ShortLinkGT applies the GT predicate on the "short_link" field.
func ShortLinkGT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldShortLink, v))
}

// ShortLinkGTE applies the GTE predicate on the "short_link" field.
func ShortLinkGTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldShortLink, v))
}

// ShortLinkLT applies the LT predicate on the "short_link" field.
func ShortLinkLT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldShortLink, v))
}

// ShortLinkLTE applies the LTE predicate on the "short_link" field.
func ShortLinkLTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldShortLink, v))
}

// ShortLinkContains applies the Contains predicate on the "short_link" field.
func ShortLinkContains(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContains(FieldShortLink, v))
}

// ShortLinkHasPrefix applies the HasPrefix predicate on the "short_link" field.
func ShortLinkHasPrefix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasPrefix(FieldShortLink, v))
}

// ShortLinkHasSuffix applies the HasSuffix predicate on the "short_link" field.
func ShortLinkHasSuffix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasSuffix(FieldShortLink, v))
}

// ShortLinkIsNil applies the IsNil predicate on the "short_link" field.
func ShortLinkIsNil() predicate.Paste {
	return predicate.Paste(sql.FieldIsNull(FieldShortLink))
}

// ShortLinkNotNil applies the NotNil predicate on the "short_link" field.
func ShortLinkNotNil() predicate.Paste {
	return predicate.Paste(sql.FieldNotNull(FieldShortLink))
}

// ShortLinkEqualFold applies the EqualFold predicate on the "short_link" field.
func ShortLinkEqualFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEqualFold(FieldShortLink, v))
}

// ShortLinkContainsFold applies the ContainsFold predicate on the "short_link" field.
func ShortLinkContainsFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContainsFold(FieldShortLink, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContainsFold(FieldContent, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Paste {
	return predicate.Paste(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Paste {
	return predicate.Paste(sql.FieldContainsFold(FieldLanguage, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldVisibility, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Paste {
	return predicate.Paste(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Paste) predicate.Paste {
	return predicate.Paste(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Paste) predicate.Paste {
	return predicate.Paste(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Paste) predicate.Paste {
	return predicate.Paste(sql.NotPredicates(p))
}
