// Code generated by ent, DO NOT EDIT.

package snippetlineage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/go-note/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldID, id))
}

// SnippetID applies equality check predicate on the "snippet_id" field. It's identical to SnippetIDEQ.
func SnippetID(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSnippetID, v))
}

// SourceSnippetID applies equality check predicate on the "source_snippet_id" field. It's identical to SourceSnippetIDEQ.
func SourceSnippetID(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceSnippetID, v))
}

// SourceShareID applies equality check predicate on the "source_share_id" field. It's identical to SourceShareIDEQ.
func SourceShareID(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceShareID, v))
}

// SourceUserID applies equality check predicate on the "source_user_id" field. It's identical to SourceUserIDEQ.
func SourceUserID(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldCreatedAt, v))
}

// SnippetIDEQ applies the EQ predicate on the "snippet_id" field.
func SnippetIDEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSnippetID, v))
}

// SnippetIDNEQ applies the NEQ predicate on the "snippet_id" field.
func SnippetIDNEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldSnippetID, v))
}

// SnippetIDIn applies the In predicate on the "snippet_id" field.
func SnippetIDIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldSnippetID, vs...))
}

// SnippetIDNotIn applies the NotIn predicate on the "snippet_id" field.
func SnippetIDNotIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldSnippetID, vs...))
}

// SnippetIDGT applies the GT predicate on the "snippet_id" field.
func SnippetIDGT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldSnippetID, v))
}

// SnippetIDGTE applies the GTE predicate on the "snippet_id" field.
func SnippetIDGTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldSnippetID, v))
}

// SnippetIDLT applies the LT predicate on the "snippet_id" field.
func SnippetIDLT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldSnippetID, v))
}

// SnippetIDLTE applies the LTE predicate on the "snippet_id" field.
func SnippetIDLTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldSnippetID, v))
}

// SourceSnippetIDEQ applies the EQ predicate on the "source_snippet_id" field.
func SourceSnippetIDEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceSnippetID, v))
}

// SourceSnippetIDNEQ applies the NEQ predicate on the "source_snippet_id" field.
func SourceSnippetIDNEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldSourceSnippetID, v))
}

// SourceSnippetIDIn applies the In predicate on the "source_snippet_id" field.
func SourceSnippetIDIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldSourceSnippetID, vs...))
}

// SourceSnippetIDNotIn applies the NotIn predicate on the "source_snippet_id" field.
func SourceSnippetIDNotIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldSourceSnippetID, vs...))
}

// SourceSnippetIDGT applies the GT predicate on the "source_snippet_id" field.
func SourceSnippetIDGT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldSourceSnippetID, v))
}

// SourceSnippetIDGTE applies the GTE predicate on the "source_snippet_id" field.
func SourceSnippetIDGTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldSourceSnippetID, v))
}

// SourceSnippetIDLT applies the LT predicate on the "source_snippet_id" field.
func SourceSnippetIDLT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldSourceSnippetID, v))
}

// SourceSnippetIDLTE applies the LTE predicate on the "source_snippet_id" field.
func SourceSnippetIDLTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldSourceSnippetID, v))
}

// SourceSnippetIDIsNil applies the IsNil predicate on the "source_snippet_id" field.
func SourceSnippetIDIsNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIsNull(FieldSourceSnippetID))
}

// SourceSnippetIDNotNil applies the NotNil predicate on the "source_snippet_id" field.
func SourceSnippetIDNotNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotNull(FieldSourceSnippetID))
}

// SourceShareIDEQ applies the EQ predicate on the "source_share_id" field.
func SourceShareIDEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceShareID, v))
}

// SourceShareIDNEQ applies the NEQ predicate on the "source_share_id" field.
func SourceShareIDNEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldSourceShareID, v))
}

// SourceShareIDIn applies the In predicate on the "source_share_id" field.
func SourceShareIDIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldSourceShareID, vs...))
}

// SourceShareIDNotIn applies the NotIn predicate on the "source_share_id" field.
func SourceShareIDNotIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldSourceShareID, vs...))
}

// SourceShareIDGT applies the GT predicate on the "source_share_id" field.
func SourceShareIDGT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldSourceShareID, v))
}

// SourceShareIDGTE applies the GTE predicate on the "source_share_id" field.
func SourceShareIDGTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldSourceShareID, v))
}

// SourceShareIDLT applies the LT predicate on the "source_share_id" field.
func SourceShareIDLT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldSourceShareID, v))
}

// SourceShareIDLTE applies the LTE predicate on the "source_share_id" field.
func SourceShareIDLTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldSourceShareID, v))
}

// SourceShareIDIsNil applies the IsNil predicate on the "source_share_id" field.
func SourceShareIDIsNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIsNull(FieldSourceShareID))
}

// SourceShareIDNotNil applies the NotNil predicate on the "source_share_id" field.
func SourceShareIDNotNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotNull(FieldSourceShareID))
}

// SourceUserIDEQ applies the EQ predicate on the "source_user_id" field.
func SourceUserIDEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldSourceUserID, v))
}

// SourceUserIDNEQ applies the NEQ predicate on the "source_user_id" field.
func SourceUserIDNEQ(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldSourceUserID, v))
}

// SourceUserIDIn applies the In predicate on the "source_user_id" field.
func SourceUserIDIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldSourceUserID, vs...))
}

// SourceUserIDNotIn applies the NotIn predicate on the "source_user_id" field.
func SourceUserIDNotIn(vs ...int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldSourceUserID, vs...))
}

// SourceUserIDGT applies the GT predicate on the "source_user_id" field.
func SourceUserIDGT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldSourceUserID, v))
}

// SourceUserIDGTE applies the GTE predicate on the "source_user_id" field.
func SourceUserIDGTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldSourceUserID, v))
}

// SourceUserIDLT applies the LT predicate on the "source_user_id" field.
func SourceUserIDLT(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldSourceUserID, v))
}

// SourceUserIDLTE applies the LTE predicate on the "source_user_id" field.
func SourceUserIDLTE(v int64) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldSourceUserID, v))
}

// SourceUserIDIsNil applies the IsNil predicate on the "source_user_id" field.
func SourceUserIDIsNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIsNull(FieldSourceUserID))
}

// SourceUserIDNotNil applies the NotNil predicate on the "source_user_id" field.
func SourceUserIDNotNil() predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotNull(FieldSourceUserID))
}

// RelationTypeEQ applies the EQ predicate on the "relation_type" field.
func RelationTypeEQ(v RelationType) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldRelationType, v))
}

// RelationTypeNEQ applies the NEQ predicate on the "relation_type" field.
func RelationTypeNEQ(v RelationType) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldRelationType, v))
}

// RelationTypeIn applies the In predicate on the "relation_type" field.
func RelationTypeIn(vs ...RelationType) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldRelationType, vs...))
}

// RelationTypeNotIn applies the NotIn predicate on the "relation_type" field.
func RelationTypeNotIn(vs ...RelationType) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldRelationType, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SnippetLineage) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SnippetLineage) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SnippetLineage) predicate.SnippetLineage {
	return predicate.SnippetLineage(sql.NotPredicates(p))
}
