// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AiCallLogsColumns holds the columns for the "ai_call_logs" table.
	AiCallLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "skill", Type: field.TypeString, Size: 64},
		{Name: "snippet_id", Type: field.TypeInt64, Nullable: true},
		{Name: "provider", Type: field.TypeString, Size: 32},
		{Name: "model", Type: field.TypeString, Size: 100},
		{Name: "prompt_version", Type: field.TypeString, Size: 32},
		{Name: "input_hash", Type: field.TypeString, Size: 64},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cost_usd", Type: field.TypeFloat64, Default: 0},
		{Name: "latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "parse_error", "llm_error", "skipped", "timeout"}},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AiCallLogsTable holds the schema information for the "ai_call_logs" table.
	AiCallLogsTable = &schema.Table{
		Name:       "ai_call_logs",
		Columns:    AiCallLogsColumns,
		PrimaryKey: []*schema.Column{AiCallLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "aicalllog_owner_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AiCallLogsColumns[1], AiCallLogsColumns[15]},
			},
			{
				Name:    "aicalllog_skill_created_at",
				Unique:  false,
				Columns: []*schema.Column{AiCallLogsColumns[2], AiCallLogsColumns[15]},
			},
			{
				Name:    "aicalllog_snippet_id",
				Unique:  false,
				Columns: []*schema.Column{AiCallLogsColumns[3]},
			},
			{
				Name:    "aicalllog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AiCallLogsColumns[15]},
			},
		},
	}
	// AiUsageDailiesColumns holds the columns for the "ai_usage_dailies" table.
	AiUsageDailiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "date", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "date", "postgres": "date", "sqlite3": "date"}},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "provider", Type: field.TypeString, Size: 32},
		{Name: "model", Type: field.TypeString, Size: 100},
		{Name: "skill", Type: field.TypeString, Size: 64},
		{Name: "call_count", Type: field.TypeInt, Default: 0},
		{Name: "success_count", Type: field.TypeInt, Default: 0},
		{Name: "error_count", Type: field.TypeInt, Default: 0},
		{Name: "input_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "cost_usd", Type: field.TypeFloat64, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AiUsageDailiesTable holds the schema information for the "ai_usage_dailies" table.
	AiUsageDailiesTable = &schema.Table{
		Name:       "ai_usage_dailies",
		Columns:    AiUsageDailiesColumns,
		PrimaryKey: []*schema.Column{AiUsageDailiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "aiusagedaily_date_owner_id_provider_model_skill",
				Unique:  true,
				Columns: []*schema.Column{AiUsageDailiesColumns[1], AiUsageDailiesColumns[2], AiUsageDailiesColumns[3], AiUsageDailiesColumns[4], AiUsageDailiesColumns[5]},
			},
			{
				Name:    "aiusagedaily_owner_id_date",
				Unique:  false,
				Columns: []*schema.Column{AiUsageDailiesColumns[2], AiUsageDailiesColumns[1]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString, Size: 60},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeInt64, Nullable: true},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_groups_children",
				Columns:    []*schema.Column{GroupsColumns[7]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "group_owner_id",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[1]},
			},
			{
				Name:    "group_owner_id_name",
				Unique:  true,
				Columns: []*schema.Column{GroupsColumns[1], GroupsColumns[2]},
			},
			{
				Name:    "group_owner_id_parent_id",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[1], GroupsColumns[7]},
			},
		},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"article", "template"}, Default: "article"},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "password_hash", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "fork_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "snippet_id", Type: field.TypeInt64},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "shares_snippets_shares",
				Columns:    []*schema.Column{SharesColumns[9]},
				RefColumns: []*schema.Column{SnippetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "share_owner_id",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[3]},
			},
			{
				Name:    "share_snippet_id",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[9]},
			},
			{
				Name:    "share_kind",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[2]},
			},
		},
	}
	// SnippetsColumns holds the columns for the "snippets" table.
	SnippetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"code", "note", "file"}, Default: "code"},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "file_url", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "file_size", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "mime_type", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "language", Type: field.TypeString, Size: 30, Default: "text"},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_favorite", Type: field.TypeBool, Default: false},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
	}
	// SnippetsTable holds the schema information for the "snippets" table.
	SnippetsTable = &schema.Table{
		Name:       "snippets",
		Columns:    SnippetsColumns,
		PrimaryKey: []*schema.Column{SnippetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "snippets_groups_snippets",
				Columns:    []*schema.Column{SnippetsColumns[14]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "snippet_owner_id",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1]},
			},
			{
				Name:    "snippet_owner_id_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1], SnippetsColumns[11]},
			},
			{
				Name:    "snippet_owner_id_is_favorite",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1], SnippetsColumns[10]},
			},
			{
				Name:    "snippet_owner_id_type",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1], SnippetsColumns[2]},
			},
			{
				Name:    "snippet_owner_id_group_id",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1], SnippetsColumns[14]},
			},
			{
				Name:    "snippet_owner_id_group_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{SnippetsColumns[1], SnippetsColumns[14], SnippetsColumns[9]},
			},
		},
	}
	// SnippetAiMetadataColumns holds the columns for the "snippet_ai_metadata" table.
	SnippetAiMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "suggested_tags", Type: field.TypeJSON, Nullable: true},
		{Name: "extracted_todos", Type: field.TypeJSON, Nullable: true},
		{Name: "content_hash", Type: field.TypeUint32, Default: 0},
		{Name: "prompt_version", Type: field.TypeString, Size: 32, Default: "v1"},
		{Name: "model", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SnippetAiMetadataTable holds the schema information for the "snippet_ai_metadata" table.
	SnippetAiMetadataTable = &schema.Table{
		Name:       "snippet_ai_metadata",
		Columns:    SnippetAiMetadataColumns,
		PrimaryKey: []*schema.Column{SnippetAiMetadataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snippetaimetadata_owner_id",
				Unique:  false,
				Columns: []*schema.Column{SnippetAiMetadataColumns[1]},
			},
		},
	}
	// SnippetLineagesColumns holds the columns for the "snippet_lineages" table.
	SnippetLineagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "snippet_id", Type: field.TypeInt64, Unique: true},
		{Name: "source_snippet_id", Type: field.TypeInt64, Nullable: true},
		{Name: "source_share_id", Type: field.TypeInt64, Nullable: true},
		{Name: "source_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "relation_type", Type: field.TypeEnum, Enums: []string{"fork", "import", "duplicate", "template"}, Default: "import"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SnippetLineagesTable holds the schema information for the "snippet_lineages" table.
	SnippetLineagesTable = &schema.Table{
		Name:       "snippet_lineages",
		Columns:    SnippetLineagesColumns,
		PrimaryKey: []*schema.Column{SnippetLineagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snippetlineage_source_snippet_id",
				Unique:  false,
				Columns: []*schema.Column{SnippetLineagesColumns[2]},
			},
			{
				Name:    "snippetlineage_source_share_id",
				Unique:  false,
				Columns: []*schema.Column{SnippetLineagesColumns[3]},
			},
			{
				Name:    "snippetlineage_relation_type",
				Unique:  false,
				Columns: []*schema.Column{SnippetLineagesColumns[5]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString, Size: 30},
		{Name: "color", Type: field.TypeString, Nullable: true, Size: 7, Default: "#6366f1"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tag_owner_id",
				Unique:  false,
				Columns: []*schema.Column{TagsColumns[1]},
			},
			{
				Name:    "tag_owner_id_name",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[1], TagsColumns[2]},
			},
		},
	}
	// TemplatesColumns holds the columns for the "templates" table.
	TemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "owner_id", Type: field.TypeInt64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500, Default: ""},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "language", Type: field.TypeString, Size: 30, Default: "markdown"},
		{Name: "category", Type: field.TypeString, Size: 30, Default: "general"},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TemplatesTable holds the schema information for the "templates" table.
	TemplatesTable = &schema.Table{
		Name:       "templates",
		Columns:    TemplatesColumns,
		PrimaryKey: []*schema.Column{TemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "template_owner_id",
				Unique:  false,
				Columns: []*schema.Column{TemplatesColumns[1]},
			},
			{
				Name:    "template_category",
				Unique:  false,
				Columns: []*schema.Column{TemplatesColumns[6]},
			},
			{
				Name:    "template_is_system",
				Unique:  false,
				Columns: []*schema.Column{TemplatesColumns[7]},
			},
		},
	}
	// SnippetTagsColumns holds the columns for the "snippet_tags" table.
	SnippetTagsColumns = []*schema.Column{
		{Name: "snippet_id", Type: field.TypeInt64},
		{Name: "tag_id", Type: field.TypeInt64},
	}
	// SnippetTagsTable holds the schema information for the "snippet_tags" table.
	SnippetTagsTable = &schema.Table{
		Name:       "snippet_tags",
		Columns:    SnippetTagsColumns,
		PrimaryKey: []*schema.Column{SnippetTagsColumns[0], SnippetTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "snippet_tags_snippet_id",
				Columns:    []*schema.Column{SnippetTagsColumns[0]},
				RefColumns: []*schema.Column{SnippetsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "snippet_tags_tag_id",
				Columns:    []*schema.Column{SnippetTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AiCallLogsTable,
		AiUsageDailiesTable,
		GroupsTable,
		SharesTable,
		SnippetsTable,
		SnippetAiMetadataTable,
		SnippetLineagesTable,
		TagsTable,
		TemplatesTable,
		SnippetTagsTable,
	}
)

func init() {
	GroupsTable.ForeignKeys[0].RefTable = GroupsTable
	SharesTable.ForeignKeys[0].RefTable = SnippetsTable
	SnippetsTable.ForeignKeys[0].RefTable = GroupsTable
	SnippetTagsTable.ForeignKeys[0].RefTable = SnippetsTable
	SnippetTagsTable.ForeignKeys[1].RefTable = TagsTable
}
