// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/aicalllog"
	"github.com/luckysxx/go-note/internal/ent/predicate"
)

// AICallLogUpdate is the builder for updating AICallLog entities.
type AICallLogUpdate struct {
	config
	hooks    []Hook
	mutation *AICallLogMutation
}

// Where appends a list predicates to the AICallLogUpdate builder.
func (_u *AICallLogUpdate) Where(ps ...predicate.AICallLog) *AICallLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *AICallLogUpdate) SetOwnerID(v int64) *AICallLogUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableOwnerID(v *int64) *AICallLogUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *AICallLogUpdate) AddOwnerID(v int64) *AICallLogUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetSkill sets the "skill" field.
func (_u *AICallLogUpdate) SetSkill(v string) *AICallLogUpdate {
	_u.mutation.SetSkill(v)
	return _u
}

// SetNillableSkill sets the "skill" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableSkill(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetSkill(*v)
	}
	return _u
}

// SetSnippetID sets the "snippet_id" field.
func (_u *AICallLogUpdate) SetSnippetID(v int64) *AICallLogUpdate {
	_u.mutation.ResetSnippetID()
	_u.mutation.SetSnippetID(v)
	return _u
}

// SetNillableSnippetID sets the "snippet_id" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableSnippetID(v *int64) *AICallLogUpdate {
	if v != nil {
		_u.SetSnippetID(*v)
	}
	return _u
}

// AddSnippetID adds value to the "snippet_id" field.
func (_u *AICallLogUpdate) AddSnippetID(v int64) *AICallLogUpdate {
	_u.mutation.AddSnippetID(v)
	return _u
}

// ClearSnippetID clears the value of the "snippet_id" field.
func (_u *AICallLogUpdate) ClearSnippetID() *AICallLogUpdate {
	_u.mutation.ClearSnippetID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AICallLogUpdate) SetProvider(v string) *AICallLogUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableProvider(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AICallLogUpdate) SetModel(v string) *AICallLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableModel(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPromptVersion sets the "prompt_version" field.
func (_u *AICallLogUpdate) SetPromptVersion(v string) *AICallLogUpdate {
	_u.mutation.SetPromptVersion(v)
	return _u
}

// SetNillablePromptVersion sets the "prompt_version" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillablePromptVersion(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetPromptVersion(*v)
	}
	return _u
}

// SetInputHash sets the "input_hash" field.
func (_u *AICallLogUpdate) SetInputHash(v string) *AICallLogUpdate {
	_u.mutation.SetInputHash(v)
	return _u
}

// SetNillableInputHash sets the "input_hash" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableInputHash(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetInputHash(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AICallLogUpdate) SetInputTokens(v int) *AICallLogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableInputTokens(v *int) *AICallLogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AICallLogUpdate) AddInputTokens(v int) *AICallLogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AICallLogUpdate) SetOutputTokens(v int) *AICallLogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableOutputTokens(v *int) *AICallLogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AICallLogUpdate) AddOutputTokens(v int) *AICallLogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *AICallLogUpdate) SetCachedTokens(v int) *AICallLogUpdate {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableCachedTokens(v *int) *AICallLogUpdate {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *AICallLogUpdate) AddCachedTokens(v int) *AICallLogUpdate {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *AICallLogUpdate) SetCostUsd(v float64) *AICallLogUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableCostUsd(v *float64) *AICallLogUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *AICallLogUpdate) AddCostUsd(v float64) *AICallLogUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *AICallLogUpdate) SetLatencyMs(v int) *AICallLogUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableLatencyMs(v *int) *AICallLogUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *AICallLogUpdate) AddLatencyMs(v int) *AICallLogUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICallLogUpdate) SetStatus(v aicalllog.Status) *AICallLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableStatus(v *aicalllog.Status) *AICallLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *AICallLogUpdate) SetError(v string) *AICallLogUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *AICallLogUpdate) SetNillableError(v *string) *AICallLogUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *AICallLogUpdate) ClearError() *AICallLogUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the AICallLogMutation object of the builder.
func (_u *AICallLogUpdate) Mutation() *AICallLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AICallLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICallLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AICallLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICallLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICallLogUpdate) check() error {
	if v, ok := _u.mutation.Skill(); ok {
		if err := aicalllog.SkillValidator(v); err != nil {
			return &ValidationError{Name: "skill", err: fmt.Errorf(`ent: validator failed for field "AICallLog.skill": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := aicalllog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AICallLog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aicalllog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AICallLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptVersion(); ok {
		if err := aicalllog.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "AICallLog.prompt_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputHash(); ok {
		if err := aicalllog.InputHashValidator(v); err != nil {
			return &ValidationError{Name: "input_hash", err: fmt.Errorf(`ent: validator failed for field "AICallLog.input_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICallLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := aicalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "AICallLog.error": %w`, err)}
		}
	}
	return nil
}

func (_u *AICallLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicalllog.Table, aicalllog.Columns, sqlgraph.NewFieldSpec(aicalllog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(aicalllog.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(aicalllog.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Skill(); ok {
		_spec.SetField(aicalllog.FieldSkill, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnippetID(); ok {
		_spec.SetField(aicalllog.FieldSnippetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnippetID(); ok {
		_spec.AddField(aicalllog.FieldSnippetID, field.TypeInt64, value)
	}
	if _u.mutation.SnippetIDCleared() {
		_spec.ClearField(aicalllog.FieldSnippetID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(aicalllog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aicalllog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptVersion(); ok {
		_spec.SetField(aicalllog.FieldPromptVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputHash(); ok {
		_spec.SetField(aicalllog.FieldInputHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(aicalllog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(aicalllog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(aicalllog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(aicalllog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(aicalllog.FieldCachedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(aicalllog.FieldCachedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(aicalllog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(aicalllog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(aicalllog.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(aicalllog.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicalllog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(aicalllog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(aicalllog.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicalllog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AICallLogUpdateOne is the builder for updating a single AICallLog entity.
type AICallLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AICallLogMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *AICallLogUpdateOne) SetOwnerID(v int64) *AICallLogUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableOwnerID(v *int64) *AICallLogUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *AICallLogUpdateOne) AddOwnerID(v int64) *AICallLogUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetSkill sets the "skill" field.
func (_u *AICallLogUpdateOne) SetSkill(v string) *AICallLogUpdateOne {
	_u.mutation.SetSkill(v)
	return _u
}

// SetNillableSkill sets the "skill" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableSkill(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetSkill(*v)
	}
	return _u
}

// SetSnippetID sets the "snippet_id" field.
func (_u *AICallLogUpdateOne) SetSnippetID(v int64) *AICallLogUpdateOne {
	_u.mutation.ResetSnippetID()
	_u.mutation.SetSnippetID(v)
	return _u
}

// SetNillableSnippetID sets the "snippet_id" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableSnippetID(v *int64) *AICallLogUpdateOne {
	if v != nil {
		_u.SetSnippetID(*v)
	}
	return _u
}

// AddSnippetID adds value to the "snippet_id" field.
func (_u *AICallLogUpdateOne) AddSnippetID(v int64) *AICallLogUpdateOne {
	_u.mutation.AddSnippetID(v)
	return _u
}

// ClearSnippetID clears the value of the "snippet_id" field.
func (_u *AICallLogUpdateOne) ClearSnippetID() *AICallLogUpdateOne {
	_u.mutation.ClearSnippetID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AICallLogUpdateOne) SetProvider(v string) *AICallLogUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableProvider(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AICallLogUpdateOne) SetModel(v string) *AICallLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableModel(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPromptVersion sets the "prompt_version" field.
func (_u *AICallLogUpdateOne) SetPromptVersion(v string) *AICallLogUpdateOne {
	_u.mutation.SetPromptVersion(v)
	return _u
}

// SetNillablePromptVersion sets the "prompt_version" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillablePromptVersion(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetPromptVersion(*v)
	}
	return _u
}

// SetInputHash sets the "input_hash" field.
func (_u *AICallLogUpdateOne) SetInputHash(v string) *AICallLogUpdateOne {
	_u.mutation.SetInputHash(v)
	return _u
}

// SetNillableInputHash sets the "input_hash" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableInputHash(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetInputHash(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AICallLogUpdateOne) SetInputTokens(v int) *AICallLogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableInputTokens(v *int) *AICallLogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AICallLogUpdateOne) AddInputTokens(v int) *AICallLogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AICallLogUpdateOne) SetOutputTokens(v int) *AICallLogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableOutputTokens(v *int) *AICallLogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AICallLogUpdateOne) AddOutputTokens(v int) *AICallLogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *AICallLogUpdateOne) SetCachedTokens(v int) *AICallLogUpdateOne {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableCachedTokens(v *int) *AICallLogUpdateOne {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *AICallLogUpdateOne) AddCachedTokens(v int) *AICallLogUpdateOne {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *AICallLogUpdateOne) SetCostUsd(v float64) *AICallLogUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableCostUsd(v *float64) *AICallLogUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *AICallLogUpdateOne) AddCostUsd(v float64) *AICallLogUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *AICallLogUpdateOne) SetLatencyMs(v int) *AICallLogUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableLatencyMs(v *int) *AICallLogUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *AICallLogUpdateOne) AddLatencyMs(v int) *AICallLogUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICallLogUpdateOne) SetStatus(v aicalllog.Status) *AICallLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableStatus(v *aicalllog.Status) *AICallLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *AICallLogUpdateOne) SetError(v string) *AICallLogUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *AICallLogUpdateOne) SetNillableError(v *string) *AICallLogUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *AICallLogUpdateOne) ClearError() *AICallLogUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the AICallLogMutation object of the builder.
func (_u *AICallLogUpdateOne) Mutation() *AICallLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AICallLogUpdate builder.
func (_u *AICallLogUpdateOne) Where(ps ...predicate.AICallLog) *AICallLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AICallLogUpdateOne) Select(field string, fields ...string) *AICallLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AICallLog entity.
func (_u *AICallLogUpdateOne) Save(ctx context.Context) (*AICallLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICallLogUpdateOne) SaveX(ctx context.Context) *AICallLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AICallLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICallLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICallLogUpdateOne) check() error {
	if v, ok := _u.mutation.Skill(); ok {
		if err := aicalllog.SkillValidator(v); err != nil {
			return &ValidationError{Name: "skill", err: fmt.Errorf(`ent: validator failed for field "AICallLog.skill": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := aicalllog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AICallLog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aicalllog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AICallLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptVersion(); ok {
		if err := aicalllog.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "AICallLog.prompt_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputHash(); ok {
		if err := aicalllog.InputHashValidator(v); err != nil {
			return &ValidationError{Name: "input_hash", err: fmt.Errorf(`ent: validator failed for field "AICallLog.input_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICallLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := aicalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "AICallLog.error": %w`, err)}
		}
	}
	return nil
}

func (_u *AICallLogUpdateOne) sqlSave(ctx context.Context) (_node *AICallLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicalllog.Table, aicalllog.Columns, sqlgraph.NewFieldSpec(aicalllog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AICallLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aicalllog.FieldID)
		for _, f := range fields {
			if !aicalllog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aicalllog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(aicalllog.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(aicalllog.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Skill(); ok {
		_spec.SetField(aicalllog.FieldSkill, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnippetID(); ok {
		_spec.SetField(aicalllog.FieldSnippetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnippetID(); ok {
		_spec.AddField(aicalllog.FieldSnippetID, field.TypeInt64, value)
	}
	if _u.mutation.SnippetIDCleared() {
		_spec.ClearField(aicalllog.FieldSnippetID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(aicalllog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aicalllog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptVersion(); ok {
		_spec.SetField(aicalllog.FieldPromptVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputHash(); ok {
		_spec.SetField(aicalllog.FieldInputHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(aicalllog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(aicalllog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(aicalllog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(aicalllog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(aicalllog.FieldCachedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(aicalllog.FieldCachedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(aicalllog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(aicalllog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(aicalllog.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(aicalllog.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicalllog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(aicalllog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(aicalllog.FieldError, field.TypeString)
	}
	_node = &AICallLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicalllog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
