// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/aicalllog"
)

// AICallLogCreate is the builder for creating a AICallLog entity.
type AICallLogCreate struct {
	config
	mutation *AICallLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwnerID sets the "owner_id" field.
func (_c *AICallLogCreate) SetOwnerID(v int64) *AICallLogCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetSkill sets the "skill" field.
func (_c *AICallLogCreate) SetSkill(v string) *AICallLogCreate {
	_c.mutation.SetSkill(v)
	return _c
}

// SetSnippetID sets the "snippet_id" field.
func (_c *AICallLogCreate) SetSnippetID(v int64) *AICallLogCreate {
	_c.mutation.SetSnippetID(v)
	return _c
}

// SetNillableSnippetID sets the "snippet_id" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableSnippetID(v *int64) *AICallLogCreate {
	if v != nil {
		_c.SetSnippetID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AICallLogCreate) SetProvider(v string) *AICallLogCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AICallLogCreate) SetModel(v string) *AICallLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetPromptVersion sets the "prompt_version" field.
func (_c *AICallLogCreate) SetPromptVersion(v string) *AICallLogCreate {
	_c.mutation.SetPromptVersion(v)
	return _c
}

// SetInputHash sets the "input_hash" field.
func (_c *AICallLogCreate) SetInputHash(v string) *AICallLogCreate {
	_c.mutation.SetInputHash(v)
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *AICallLogCreate) SetInputTokens(v int) *AICallLogCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableInputTokens(v *int) *AICallLogCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *AICallLogCreate) SetOutputTokens(v int) *AICallLogCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableOutputTokens(v *int) *AICallLogCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetCachedTokens sets the "cached_tokens" field.
func (_c *AICallLogCreate) SetCachedTokens(v int) *AICallLogCreate {
	_c.mutation.SetCachedTokens(v)
	return _c
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableCachedTokens(v *int) *AICallLogCreate {
	if v != nil {
		_c.SetCachedTokens(*v)
	}
	return _c
}

// SetCostUsd sets the "cost_usd" field.
func (_c *AICallLogCreate) SetCostUsd(v float64) *AICallLogCreate {
	_c.mutation.SetCostUsd(v)
	return _c
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableCostUsd(v *float64) *AICallLogCreate {
	if v != nil {
		_c.SetCostUsd(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *AICallLogCreate) SetLatencyMs(v int) *AICallLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableLatencyMs(v *int) *AICallLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AICallLogCreate) SetStatus(v aicalllog.Status) *AICallLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetError sets the "error" field.
func (_c *AICallLogCreate) SetError(v string) *AICallLogCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableError(v *string) *AICallLogCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AICallLogCreate) SetCreatedAt(v time.Time) *AICallLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AICallLogCreate) SetNillableCreatedAt(v *time.Time) *AICallLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AICallLogCreate) SetID(v int64) *AICallLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AICallLogMutation object of the builder.
func (_c *AICallLogCreate) Mutation() *AICallLogMutation {
	return _c.mutation
}

// Save creates the AICallLog in the database.
func (_c *AICallLogCreate) Save(ctx context.Context) (*AICallLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AICallLogCreate) SaveX(ctx context.Context) *AICallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICallLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICallLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AICallLogCreate) defaults() {
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := aicalllog.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := aicalllog.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		v := aicalllog.DefaultCachedTokens
		_c.mutation.SetCachedTokens(v)
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		v := aicalllog.DefaultCostUsd
		_c.mutation.SetCostUsd(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := aicalllog.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aicalllog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AICallLogCreate) check() error {
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "AICallLog.owner_id"`)}
	}
	if _, ok := _c.mutation.Skill(); !ok {
		return &ValidationError{Name: "skill", err: errors.New(`ent: missing required field "AICallLog.skill"`)}
	}
	if v, ok := _c.mutation.Skill(); ok {
		if err := aicalllog.SkillValidator(v); err != nil {
			return &ValidationError{Name: "skill", err: fmt.Errorf(`ent: validator failed for field "AICallLog.skill": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AICallLog.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := aicalllog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AICallLog.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AICallLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := aicalllog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AICallLog.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromptVersion(); !ok {
		return &ValidationError{Name: "prompt_version", err: errors.New(`ent: missing required field "AICallLog.prompt_version"`)}
	}
	if v, ok := _c.mutation.PromptVersion(); ok {
		if err := aicalllog.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "AICallLog.prompt_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputHash(); !ok {
		return &ValidationError{Name: "input_hash", err: errors.New(`ent: missing required field "AICallLog.input_hash"`)}
	}
	if v, ok := _c.mutation.InputHash(); ok {
		if err := aicalllog.InputHashValidator(v); err != nil {
			return &ValidationError{Name: "input_hash", err: fmt.Errorf(`ent: validator failed for field "AICallLog.input_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "AICallLog.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "AICallLog.output_tokens"`)}
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		return &ValidationError{Name: "cached_tokens", err: errors.New(`ent: missing required field "AICallLog.cached_tokens"`)}
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		return &ValidationError{Name: "cost_usd", err: errors.New(`ent: missing required field "AICallLog.cost_usd"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "AICallLog.latency_ms"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AICallLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := aicalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICallLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Error(); ok {
		if err := aicalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "AICallLog.error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AICallLog.created_at"`)}
	}
	return nil
}

func (_c *AICallLogCreate) sqlSave(ctx context.Context) (*AICallLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AICallLogCreate) createSpec() (*AICallLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AICallLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aicalllog.Table, sqlgraph.NewFieldSpec(aicalllog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(aicalllog.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Skill(); ok {
		_spec.SetField(aicalllog.FieldSkill, field.TypeString, value)
		_node.Skill = value
	}
	if value, ok := _c.mutation.SnippetID(); ok {
		_spec.SetField(aicalllog.FieldSnippetID, field.TypeInt64, value)
		_node.SnippetID = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(aicalllog.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(aicalllog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.PromptVersion(); ok {
		_spec.SetField(aicalllog.FieldPromptVersion, field.TypeString, value)
		_node.PromptVersion = value
	}
	if value, ok := _c.mutation.InputHash(); ok {
		_spec.SetField(aicalllog.FieldInputHash, field.TypeString, value)
		_node.InputHash = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(aicalllog.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(aicalllog.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CachedTokens(); ok {
		_spec.SetField(aicalllog.FieldCachedTokens, field.TypeInt, value)
		_node.CachedTokens = value
	}
	if value, ok := _c.mutation.CostUsd(); ok {
		_spec.SetField(aicalllog.FieldCostUsd, field.TypeFloat64, value)
		_node.CostUsd = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(aicalllog.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(aicalllog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(aicalllog.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aicalllog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AICallLog.Create().
//		SetOwnerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AICallLogUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *AICallLogCreate) OnConflict(opts ...sql.ConflictOption) *AICallLogUpsertOne {
	_c.conflict = opts
	return &AICallLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AICallLogCreate) OnConflictColumns(columns ...string) *AICallLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AICallLogUpsertOne{
		create: _c,
	}
}

type (
	// AICallLogUpsertOne is the builder for "upsert"-ing
	//  one AICallLog node.
	AICallLogUpsertOne struct {
		create *AICallLogCreate
	}

	// AICallLogUpsert is the "OnConflict" setter.
	AICallLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwnerID sets the "owner_id" field.
func (u *AICallLogUpsert) SetOwnerID(v int64) *AICallLogUpsert {
	u.Set(aicalllog.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateOwnerID() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldOwnerID)
	return u
}

// AddOwnerID adds v to the "owner_id" field.
func (u *AICallLogUpsert) AddOwnerID(v int64) *AICallLogUpsert {
	u.Add(aicalllog.FieldOwnerID, v)
	return u
}

// SetSkill sets the "skill" field.
func (u *AICallLogUpsert) SetSkill(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldSkill, v)
	return u
}

// UpdateSkill sets the "skill" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateSkill() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldSkill)
	return u
}

// SetSnippetID sets the "snippet_id" field.
func (u *AICallLogUpsert) SetSnippetID(v int64) *AICallLogUpsert {
	u.Set(aicalllog.FieldSnippetID, v)
	return u
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateSnippetID() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldSnippetID)
	return u
}

// AddSnippetID adds v to the "snippet_id" field.
func (u *AICallLogUpsert) AddSnippetID(v int64) *AICallLogUpsert {
	u.Add(aicalllog.FieldSnippetID, v)
	return u
}

// ClearSnippetID clears the value of the "snippet_id" field.
func (u *AICallLogUpsert) ClearSnippetID() *AICallLogUpsert {
	u.SetNull(aicalllog.FieldSnippetID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AICallLogUpsert) SetProvider(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateProvider() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *AICallLogUpsert) SetModel(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateModel() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldModel)
	return u
}

// SetPromptVersion sets the "prompt_version" field.
func (u *AICallLogUpsert) SetPromptVersion(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldPromptVersion, v)
	return u
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdatePromptVersion() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldPromptVersion)
	return u
}

// SetInputHash sets the "input_hash" field.
func (u *AICallLogUpsert) SetInputHash(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldInputHash, v)
	return u
}

// UpdateInputHash sets the "input_hash" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateInputHash() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldInputHash)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *AICallLogUpsert) SetInputTokens(v int) *AICallLogUpsert {
	u.Set(aicalllog.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateInputTokens() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *AICallLogUpsert) AddInputTokens(v int) *AICallLogUpsert {
	u.Add(aicalllog.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *AICallLogUpsert) SetOutputTokens(v int) *AICallLogUpsert {
	u.Set(aicalllog.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateOutputTokens() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *AICallLogUpsert) AddOutputTokens(v int) *AICallLogUpsert {
	u.Add(aicalllog.FieldOutputTokens, v)
	return u
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *AICallLogUpsert) SetCachedTokens(v int) *AICallLogUpsert {
	u.Set(aicalllog.FieldCachedTokens, v)
	return u
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateCachedTokens() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldCachedTokens)
	return u
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *AICallLogUpsert) AddCachedTokens(v int) *AICallLogUpsert {
	u.Add(aicalllog.FieldCachedTokens, v)
	return u
}

// SetCostUsd sets the "cost_usd" field.
func (u *AICallLogUpsert) SetCostUsd(v float64) *AICallLogUpsert {
	u.Set(aicalllog.FieldCostUsd, v)
	return u
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateCostUsd() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldCostUsd)
	return u
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AICallLogUpsert) AddCostUsd(v float64) *AICallLogUpsert {
	u.Add(aicalllog.FieldCostUsd, v)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AICallLogUpsert) SetLatencyMs(v int) *AICallLogUpsert {
	u.Set(aicalllog.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateLatencyMs() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AICallLogUpsert) AddLatencyMs(v int) *AICallLogUpsert {
	u.Add(aicalllog.FieldLatencyMs, v)
	return u
}

// SetStatus sets the "status" field.
func (u *AICallLogUpsert) SetStatus(v aicalllog.Status) *AICallLogUpsert {
	u.Set(aicalllog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateStatus() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *AICallLogUpsert) SetError(v string) *AICallLogUpsert {
	u.Set(aicalllog.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *AICallLogUpsert) UpdateError() *AICallLogUpsert {
	u.SetExcluded(aicalllog.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *AICallLogUpsert) ClearError() *AICallLogUpsert {
	u.SetNull(aicalllog.FieldError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aicalllog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AICallLogUpsertOne) UpdateNewValues() *AICallLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(aicalllog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(aicalllog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AICallLogUpsertOne) Ignore() *AICallLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AICallLogUpsertOne) DoNothing() *AICallLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AICallLogCreate.OnConflict
// documentation for more info.
func (u *AICallLogUpsertOne) Update(set func(*AICallLogUpsert)) *AICallLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AICallLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *AICallLogUpsertOne) SetOwnerID(v int64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *AICallLogUpsertOne) AddOwnerID(v int64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateOwnerID() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateOwnerID()
	})
}

// SetSkill sets the "skill" field.
func (u *AICallLogUpsertOne) SetSkill(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetSkill(v)
	})
}

// UpdateSkill sets the "skill" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateSkill() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateSkill()
	})
}

// SetSnippetID sets the "snippet_id" field.
func (u *AICallLogUpsertOne) SetSnippetID(v int64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetSnippetID(v)
	})
}

// AddSnippetID adds v to the "snippet_id" field.
func (u *AICallLogUpsertOne) AddSnippetID(v int64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddSnippetID(v)
	})
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateSnippetID() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateSnippetID()
	})
}

// ClearSnippetID clears the value of the "snippet_id" field.
func (u *AICallLogUpsertOne) ClearSnippetID() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.ClearSnippetID()
	})
}

// SetProvider sets the "provider" field.
func (u *AICallLogUpsertOne) SetProvider(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateProvider() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *AICallLogUpsertOne) SetModel(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateModel() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateModel()
	})
}

// SetPromptVersion sets the "prompt_version" field.
func (u *AICallLogUpsertOne) SetPromptVersion(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetPromptVersion(v)
	})
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdatePromptVersion() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdatePromptVersion()
	})
}

// SetInputHash sets the "input_hash" field.
func (u *AICallLogUpsertOne) SetInputHash(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetInputHash(v)
	})
}

// UpdateInputHash sets the "input_hash" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateInputHash() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateInputHash()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *AICallLogUpsertOne) SetInputTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *AICallLogUpsertOne) AddInputTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateInputTokens() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *AICallLogUpsertOne) SetOutputTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *AICallLogUpsertOne) AddOutputTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateOutputTokens() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *AICallLogUpsertOne) SetCachedTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *AICallLogUpsertOne) AddCachedTokens(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateCachedTokens() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *AICallLogUpsertOne) SetCostUsd(v float64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AICallLogUpsertOne) AddCostUsd(v float64) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateCostUsd() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateCostUsd()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AICallLogUpsertOne) SetLatencyMs(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AICallLogUpsertOne) AddLatencyMs(v int) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateLatencyMs() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetStatus sets the "status" field.
func (u *AICallLogUpsertOne) SetStatus(v aicalllog.Status) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateStatus() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *AICallLogUpsertOne) SetError(v string) *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *AICallLogUpsertOne) UpdateError() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *AICallLogUpsertOne) ClearError() *AICallLogUpsertOne {
	return u.Update(func(s *AICallLogUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *AICallLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AICallLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AICallLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AICallLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AICallLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AICallLogCreateBulk is the builder for creating many AICallLog entities in bulk.
type AICallLogCreateBulk struct {
	config
	err      error
	builders []*AICallLogCreate
	conflict []sql.ConflictOption
}

// Save creates the AICallLog entities in the database.
func (_c *AICallLogCreateBulk) Save(ctx context.Context) ([]*AICallLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AICallLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AICallLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AICallLogCreateBulk) SaveX(ctx context.Context) []*AICallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICallLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICallLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AICallLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AICallLogUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *AICallLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *AICallLogUpsertBulk {
	_c.conflict = opts
	return &AICallLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AICallLogCreateBulk) OnConflictColumns(columns ...string) *AICallLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AICallLogUpsertBulk{
		create: _c,
	}
}

// AICallLogUpsertBulk is the builder for "upsert"-ing
// a bulk of AICallLog nodes.
type AICallLogUpsertBulk struct {
	create *AICallLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aicalllog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AICallLogUpsertBulk) UpdateNewValues() *AICallLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(aicalllog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(aicalllog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AICallLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AICallLogUpsertBulk) Ignore() *AICallLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AICallLogUpsertBulk) DoNothing() *AICallLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AICallLogCreateBulk.OnConflict
// documentation for more info.
func (u *AICallLogUpsertBulk) Update(set func(*AICallLogUpsert)) *AICallLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AICallLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *AICallLogUpsertBulk) SetOwnerID(v int64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *AICallLogUpsertBulk) AddOwnerID(v int64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateOwnerID() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateOwnerID()
	})
}

// SetSkill sets the "skill" field.
func (u *AICallLogUpsertBulk) SetSkill(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetSkill(v)
	})
}

// UpdateSkill sets the "skill" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateSkill() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateSkill()
	})
}

// SetSnippetID sets the "snippet_id" field.
func (u *AICallLogUpsertBulk) SetSnippetID(v int64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetSnippetID(v)
	})
}

// AddSnippetID adds v to the "snippet_id" field.
func (u *AICallLogUpsertBulk) AddSnippetID(v int64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddSnippetID(v)
	})
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateSnippetID() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateSnippetID()
	})
}

// ClearSnippetID clears the value of the "snippet_id" field.
func (u *AICallLogUpsertBulk) ClearSnippetID() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.ClearSnippetID()
	})
}

// SetProvider sets the "provider" field.
func (u *AICallLogUpsertBulk) SetProvider(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateProvider() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *AICallLogUpsertBulk) SetModel(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateModel() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateModel()
	})
}

// SetPromptVersion sets the "prompt_version" field.
func (u *AICallLogUpsertBulk) SetPromptVersion(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetPromptVersion(v)
	})
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdatePromptVersion() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdatePromptVersion()
	})
}

// SetInputHash sets the "input_hash" field.
func (u *AICallLogUpsertBulk) SetInputHash(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetInputHash(v)
	})
}

// UpdateInputHash sets the "input_hash" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateInputHash() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateInputHash()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *AICallLogUpsertBulk) SetInputTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *AICallLogUpsertBulk) AddInputTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateInputTokens() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *AICallLogUpsertBulk) SetOutputTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *AICallLogUpsertBulk) AddOutputTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateOutputTokens() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *AICallLogUpsertBulk) SetCachedTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *AICallLogUpsertBulk) AddCachedTokens(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateCachedTokens() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *AICallLogUpsertBulk) SetCostUsd(v float64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AICallLogUpsertBulk) AddCostUsd(v float64) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateCostUsd() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateCostUsd()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *AICallLogUpsertBulk) SetLatencyMs(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *AICallLogUpsertBulk) AddLatencyMs(v int) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateLatencyMs() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetStatus sets the "status" field.
func (u *AICallLogUpsertBulk) SetStatus(v aicalllog.Status) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateStatus() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *AICallLogUpsertBulk) SetError(v string) *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *AICallLogUpsertBulk) UpdateError() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *AICallLogUpsertBulk) ClearError() *AICallLogUpsertBulk {
	return u.Update(func(s *AICallLogUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *AICallLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AICallLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AICallLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AICallLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
