// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/luckysxx/go-note/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/luckysxx/go-note/internal/ent/aicalllog"
	"github.com/luckysxx/go-note/internal/ent/aiusagedaily"
	"github.com/luckysxx/go-note/internal/ent/group"
	"github.com/luckysxx/go-note/internal/ent/share"
	"github.com/luckysxx/go-note/internal/ent/snippet"
	"github.com/luckysxx/go-note/internal/ent/snippetaimetadata"
	"github.com/luckysxx/go-note/internal/ent/snippetlineage"
	"github.com/luckysxx/go-note/internal/ent/tag"
	"github.com/luckysxx/go-note/internal/ent/template"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AICallLog is the client for interacting with the AICallLog builders.
	AICallLog *AICallLogClient
	// AIUsageDaily is the client for interacting with the AIUsageDaily builders.
	AIUsageDaily *AIUsageDailyClient
	// Group is the client for interacting with the Group builders.
	Group *GroupClient
	// Share is the client for interacting with the Share builders.
	Share *ShareClient
	// Snippet is the client for interacting with the Snippet builders.
	Snippet *SnippetClient
	// SnippetAIMetadata is the client for interacting with the SnippetAIMetadata builders.
	SnippetAIMetadata *SnippetAIMetadataClient
	// SnippetLineage is the client for interacting with the SnippetLineage builders.
	SnippetLineage *SnippetLineageClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// Template is the client for interacting with the Template builders.
	Template *TemplateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AICallLog = NewAICallLogClient(c.config)
	c.AIUsageDaily = NewAIUsageDailyClient(c.config)
	c.Group = NewGroupClient(c.config)
	c.Share = NewShareClient(c.config)
	c.Snippet = NewSnippetClient(c.config)
	c.SnippetAIMetadata = NewSnippetAIMetadataClient(c.config)
	c.SnippetLineage = NewSnippetLineageClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.Template = NewTemplateClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		AICallLog:         NewAICallLogClient(cfg),
		AIUsageDaily:      NewAIUsageDailyClient(cfg),
		Group:             NewGroupClient(cfg),
		Share:             NewShareClient(cfg),
		Snippet:           NewSnippetClient(cfg),
		SnippetAIMetadata: NewSnippetAIMetadataClient(cfg),
		SnippetLineage:    NewSnippetLineageClient(cfg),
		Tag:               NewTagClient(cfg),
		Template:          NewTemplateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		AICallLog:         NewAICallLogClient(cfg),
		AIUsageDaily:      NewAIUsageDailyClient(cfg),
		Group:             NewGroupClient(cfg),
		Share:             NewShareClient(cfg),
		Snippet:           NewSnippetClient(cfg),
		SnippetAIMetadata: NewSnippetAIMetadataClient(cfg),
		SnippetLineage:    NewSnippetLineageClient(cfg),
		Tag:               NewTagClient(cfg),
		Template:          NewTemplateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AICallLog.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AICallLog, c.AIUsageDaily, c.Group, c.Share, c.Snippet, c.SnippetAIMetadata,
		c.SnippetLineage, c.Tag, c.Template,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AICallLog, c.AIUsageDaily, c.Group, c.Share, c.Snippet, c.SnippetAIMetadata,
		c.SnippetLineage, c.Tag, c.Template,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AICallLogMutation:
		return c.AICallLog.mutate(ctx, m)
	case *AIUsageDailyMutation:
		return c.AIUsageDaily.mutate(ctx, m)
	case *GroupMutation:
		return c.Group.mutate(ctx, m)
	case *ShareMutation:
		return c.Share.mutate(ctx, m)
	case *SnippetMutation:
		return c.Snippet.mutate(ctx, m)
	case *SnippetAIMetadataMutation:
		return c.SnippetAIMetadata.mutate(ctx, m)
	case *SnippetLineageMutation:
		return c.SnippetLineage.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	case *TemplateMutation:
		return c.Template.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AICallLogClient is a client for the AICallLog schema.
type AICallLogClient struct {
	config
}

// NewAICallLogClient returns a client for the AICallLog from the given config.
func NewAICallLogClient(c config) *AICallLogClient {
	return &AICallLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aicalllog.Hooks(f(g(h())))`.
func (c *AICallLogClient) Use(hooks ...Hook) {
	c.hooks.AICallLog = append(c.hooks.AICallLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `aicalllog.Intercept(f(g(h())))`.
func (c *AICallLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.AICallLog = append(c.inters.AICallLog, interceptors...)
}

// Create returns a builder for creating a AICallLog entity.
func (c *AICallLogClient) Create() *AICallLogCreate {
	mutation := newAICallLogMutation(c.config, OpCreate)
	return &AICallLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AICallLog entities.
func (c *AICallLogClient) CreateBulk(builders ...*AICallLogCreate) *AICallLogCreateBulk {
	return &AICallLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AICallLogClient) MapCreateBulk(slice any, setFunc func(*AICallLogCreate, int)) *AICallLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AICallLogCreateBulk{err: fmt.Errorf("calling to AICallLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AICallLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AICallLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AICallLog.
func (c *AICallLogClient) Update() *AICallLogUpdate {
	mutation := newAICallLogMutation(c.config, OpUpdate)
	return &AICallLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AICallLogClient) UpdateOne(_m *AICallLog) *AICallLogUpdateOne {
	mutation := newAICallLogMutation(c.config, OpUpdateOne, withAICallLog(_m))
	return &AICallLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AICallLogClient) UpdateOneID(id int64) *AICallLogUpdateOne {
	mutation := newAICallLogMutation(c.config, OpUpdateOne, withAICallLogID(id))
	return &AICallLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AICallLog.
func (c *AICallLogClient) Delete() *AICallLogDelete {
	mutation := newAICallLogMutation(c.config, OpDelete)
	return &AICallLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AICallLogClient) DeleteOne(_m *AICallLog) *AICallLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AICallLogClient) DeleteOneID(id int64) *AICallLogDeleteOne {
	builder := c.Delete().Where(aicalllog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AICallLogDeleteOne{builder}
}

// Query returns a query builder for AICallLog.
func (c *AICallLogClient) Query() *AICallLogQuery {
	return &AICallLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAICallLog},
		inters: c.Interceptors(),
	}
}

// Get returns a AICallLog entity by its id.
func (c *AICallLogClient) Get(ctx context.Context, id int64) (*AICallLog, error) {
	return c.Query().Where(aicalllog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AICallLogClient) GetX(ctx context.Context, id int64) *AICallLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AICallLogClient) Hooks() []Hook {
	return c.hooks.AICallLog
}

// Interceptors returns the client interceptors.
func (c *AICallLogClient) Interceptors() []Interceptor {
	return c.inters.AICallLog
}

func (c *AICallLogClient) mutate(ctx context.Context, m *AICallLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AICallLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AICallLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AICallLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AICallLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AICallLog mutation op: %q", m.Op())
	}
}

// AIUsageDailyClient is a client for the AIUsageDaily schema.
type AIUsageDailyClient struct {
	config
}

// NewAIUsageDailyClient returns a client for the AIUsageDaily from the given config.
func NewAIUsageDailyClient(c config) *AIUsageDailyClient {
	return &AIUsageDailyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aiusagedaily.Hooks(f(g(h())))`.
func (c *AIUsageDailyClient) Use(hooks ...Hook) {
	c.hooks.AIUsageDaily = append(c.hooks.AIUsageDaily, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `aiusagedaily.Intercept(f(g(h())))`.
func (c *AIUsageDailyClient) Intercept(interceptors ...Interceptor) {
	c.inters.AIUsageDaily = append(c.inters.AIUsageDaily, interceptors...)
}

// Create returns a builder for creating a AIUsageDaily entity.
func (c *AIUsageDailyClient) Create() *AIUsageDailyCreate {
	mutation := newAIUsageDailyMutation(c.config, OpCreate)
	return &AIUsageDailyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AIUsageDaily entities.
func (c *AIUsageDailyClient) CreateBulk(builders ...*AIUsageDailyCreate) *AIUsageDailyCreateBulk {
	return &AIUsageDailyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AIUsageDailyClient) MapCreateBulk(slice any, setFunc func(*AIUsageDailyCreate, int)) *AIUsageDailyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AIUsageDailyCreateBulk{err: fmt.Errorf("calling to AIUsageDailyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AIUsageDailyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AIUsageDailyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AIUsageDaily.
func (c *AIUsageDailyClient) Update() *AIUsageDailyUpdate {
	mutation := newAIUsageDailyMutation(c.config, OpUpdate)
	return &AIUsageDailyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AIUsageDailyClient) UpdateOne(_m *AIUsageDaily) *AIUsageDailyUpdateOne {
	mutation := newAIUsageDailyMutation(c.config, OpUpdateOne, withAIUsageDaily(_m))
	return &AIUsageDailyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AIUsageDailyClient) UpdateOneID(id int64) *AIUsageDailyUpdateOne {
	mutation := newAIUsageDailyMutation(c.config, OpUpdateOne, withAIUsageDailyID(id))
	return &AIUsageDailyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AIUsageDaily.
func (c *AIUsageDailyClient) Delete() *AIUsageDailyDelete {
	mutation := newAIUsageDailyMutation(c.config, OpDelete)
	return &AIUsageDailyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AIUsageDailyClient) DeleteOne(_m *AIUsageDaily) *AIUsageDailyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AIUsageDailyClient) DeleteOneID(id int64) *AIUsageDailyDeleteOne {
	builder := c.Delete().Where(aiusagedaily.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AIUsageDailyDeleteOne{builder}
}

// Query returns a query builder for AIUsageDaily.
func (c *AIUsageDailyClient) Query() *AIUsageDailyQuery {
	return &AIUsageDailyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAIUsageDaily},
		inters: c.Interceptors(),
	}
}

// Get returns a AIUsageDaily entity by its id.
func (c *AIUsageDailyClient) Get(ctx context.Context, id int64) (*AIUsageDaily, error) {
	return c.Query().Where(aiusagedaily.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AIUsageDailyClient) GetX(ctx context.Context, id int64) *AIUsageDaily {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AIUsageDailyClient) Hooks() []Hook {
	return c.hooks.AIUsageDaily
}

// Interceptors returns the client interceptors.
func (c *AIUsageDailyClient) Interceptors() []Interceptor {
	return c.inters.AIUsageDaily
}

func (c *AIUsageDailyClient) mutate(ctx context.Context, m *AIUsageDailyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AIUsageDailyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AIUsageDailyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AIUsageDailyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AIUsageDailyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AIUsageDaily mutation op: %q", m.Op())
	}
}

// GroupClient is a client for the Group schema.
type GroupClient struct {
	config
}

// NewGroupClient returns a client for the Group from the given config.
func NewGroupClient(c config) *GroupClient {
	return &GroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `group.Hooks(f(g(h())))`.
func (c *GroupClient) Use(hooks ...Hook) {
	c.hooks.Group = append(c.hooks.Group, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `group.Intercept(f(g(h())))`.
func (c *GroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.Group = append(c.inters.Group, interceptors...)
}

// Create returns a builder for creating a Group entity.
func (c *GroupClient) Create() *GroupCreate {
	mutation := newGroupMutation(c.config, OpCreate)
	return &GroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Group entities.
func (c *GroupClient) CreateBulk(builders ...*GroupCreate) *GroupCreateBulk {
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupClient) MapCreateBulk(slice any, setFunc func(*GroupCreate, int)) *GroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupCreateBulk{err: fmt.Errorf("calling to GroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Group.
func (c *GroupClient) Update() *GroupUpdate {
	mutation := newGroupMutation(c.config, OpUpdate)
	return &GroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupClient) UpdateOne(_m *Group) *GroupUpdateOne {
	mutation := newGroupMutation(c.config, OpUpdateOne, withGroup(_m))
	return &GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupClient) UpdateOneID(id int64) *GroupUpdateOne {
	mutation := newGroupMutation(c.config, OpUpdateOne, withGroupID(id))
	return &GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Group.
func (c *GroupClient) Delete() *GroupDelete {
	mutation := newGroupMutation(c.config, OpDelete)
	return &GroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupClient) DeleteOne(_m *Group) *GroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupClient) DeleteOneID(id int64) *GroupDeleteOne {
	builder := c.Delete().Where(group.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupDeleteOne{builder}
}

// Query returns a query builder for Group.
func (c *GroupClient) Query() *GroupQuery {
	return &GroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a Group entity by its id.
func (c *GroupClient) Get(ctx context.Context, id int64) (*Group, error) {
	return c.Query().Where(group.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupClient) GetX(ctx context.Context, id int64) *Group {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySnippets queries the snippets edge of a Group.
func (c *GroupClient) QuerySnippets(_m *Group) *SnippetQuery {
	query := (&SnippetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(group.Table, group.FieldID, id),
			sqlgraph.To(snippet.Table, snippet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, group.SnippetsTable, group.SnippetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a Group.
func (c *GroupClient) QueryParent(_m *Group) *GroupQuery {
	query := (&GroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(group.Table, group.FieldID, id),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, group.ParentTable, group.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a Group.
func (c *GroupClient) QueryChildren(_m *Group) *GroupQuery {
	query := (&GroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(group.Table, group.FieldID, id),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, group.ChildrenTable, group.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GroupClient) Hooks() []Hook {
	return c.hooks.Group
}

// Interceptors returns the client interceptors.
func (c *GroupClient) Interceptors() []Interceptor {
	return c.inters.Group
}

func (c *GroupClient) mutate(ctx context.Context, m *GroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Group mutation op: %q", m.Op())
	}
}

// ShareClient is a client for the Share schema.
type ShareClient struct {
	config
}

// NewShareClient returns a client for the Share from the given config.
func NewShareClient(c config) *ShareClient {
	return &ShareClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `share.Hooks(f(g(h())))`.
func (c *ShareClient) Use(hooks ...Hook) {
	c.hooks.Share = append(c.hooks.Share, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `share.Intercept(f(g(h())))`.
func (c *ShareClient) Intercept(interceptors ...Interceptor) {
	c.inters.Share = append(c.inters.Share, interceptors...)
}

// Create returns a builder for creating a Share entity.
func (c *ShareClient) Create() *ShareCreate {
	mutation := newShareMutation(c.config, OpCreate)
	return &ShareCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Share entities.
func (c *ShareClient) CreateBulk(builders ...*ShareCreate) *ShareCreateBulk {
	return &ShareCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ShareClient) MapCreateBulk(slice any, setFunc func(*ShareCreate, int)) *ShareCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ShareCreateBulk{err: fmt.Errorf("calling to ShareClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ShareCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ShareCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Share.
func (c *ShareClient) Update() *ShareUpdate {
	mutation := newShareMutation(c.config, OpUpdate)
	return &ShareUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShareClient) UpdateOne(_m *Share) *ShareUpdateOne {
	mutation := newShareMutation(c.config, OpUpdateOne, withShare(_m))
	return &ShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShareClient) UpdateOneID(id int64) *ShareUpdateOne {
	mutation := newShareMutation(c.config, OpUpdateOne, withShareID(id))
	return &ShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Share.
func (c *ShareClient) Delete() *ShareDelete {
	mutation := newShareMutation(c.config, OpDelete)
	return &ShareDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ShareClient) DeleteOne(_m *Share) *ShareDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ShareClient) DeleteOneID(id int64) *ShareDeleteOne {
	builder := c.Delete().Where(share.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShareDeleteOne{builder}
}

// Query returns a query builder for Share.
func (c *ShareClient) Query() *ShareQuery {
	return &ShareQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeShare},
		inters: c.Interceptors(),
	}
}

// Get returns a Share entity by its id.
func (c *ShareClient) Get(ctx context.Context, id int64) (*Share, error) {
	return c.Query().Where(share.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShareClient) GetX(ctx context.Context, id int64) *Share {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySnippet queries the snippet edge of a Share.
func (c *ShareClient) QuerySnippet(_m *Share) *SnippetQuery {
	query := (&SnippetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(share.Table, share.FieldID, id),
			sqlgraph.To(snippet.Table, snippet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, share.SnippetTable, share.SnippetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ShareClient) Hooks() []Hook {
	return c.hooks.Share
}

// Interceptors returns the client interceptors.
func (c *ShareClient) Interceptors() []Interceptor {
	return c.inters.Share
}

func (c *ShareClient) mutate(ctx context.Context, m *ShareMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ShareCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ShareUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ShareDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Share mutation op: %q", m.Op())
	}
}

// SnippetClient is a client for the Snippet schema.
type SnippetClient struct {
	config
}

// NewSnippetClient returns a client for the Snippet from the given config.
func NewSnippetClient(c config) *SnippetClient {
	return &SnippetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `snippet.Hooks(f(g(h())))`.
func (c *SnippetClient) Use(hooks ...Hook) {
	c.hooks.Snippet = append(c.hooks.Snippet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `snippet.Intercept(f(g(h())))`.
func (c *SnippetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Snippet = append(c.inters.Snippet, interceptors...)
}

// Create returns a builder for creating a Snippet entity.
func (c *SnippetClient) Create() *SnippetCreate {
	mutation := newSnippetMutation(c.config, OpCreate)
	return &SnippetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Snippet entities.
func (c *SnippetClient) CreateBulk(builders ...*SnippetCreate) *SnippetCreateBulk {
	return &SnippetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SnippetClient) MapCreateBulk(slice any, setFunc func(*SnippetCreate, int)) *SnippetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SnippetCreateBulk{err: fmt.Errorf("calling to SnippetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SnippetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SnippetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Snippet.
func (c *SnippetClient) Update() *SnippetUpdate {
	mutation := newSnippetMutation(c.config, OpUpdate)
	return &SnippetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SnippetClient) UpdateOne(_m *Snippet) *SnippetUpdateOne {
	mutation := newSnippetMutation(c.config, OpUpdateOne, withSnippet(_m))
	return &SnippetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SnippetClient) UpdateOneID(id int64) *SnippetUpdateOne {
	mutation := newSnippetMutation(c.config, OpUpdateOne, withSnippetID(id))
	return &SnippetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Snippet.
func (c *SnippetClient) Delete() *SnippetDelete {
	mutation := newSnippetMutation(c.config, OpDelete)
	return &SnippetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SnippetClient) DeleteOne(_m *Snippet) *SnippetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SnippetClient) DeleteOneID(id int64) *SnippetDeleteOne {
	builder := c.Delete().Where(snippet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SnippetDeleteOne{builder}
}

// Query returns a query builder for Snippet.
func (c *SnippetClient) Query() *SnippetQuery {
	return &SnippetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSnippet},
		inters: c.Interceptors(),
	}
}

// Get returns a Snippet entity by its id.
func (c *SnippetClient) Get(ctx context.Context, id int64) (*Snippet, error) {
	return c.Query().Where(snippet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SnippetClient) GetX(ctx context.Context, id int64) *Snippet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGroup queries the group edge of a Snippet.
func (c *SnippetClient) QueryGroup(_m *Snippet) *GroupQuery {
	query := (&GroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(snippet.Table, snippet.FieldID, id),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, snippet.GroupTable, snippet.GroupColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Snippet.
func (c *SnippetClient) QueryTags(_m *Snippet) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(snippet.Table, snippet.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, snippet.TagsTable, snippet.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShares queries the shares edge of a Snippet.
func (c *SnippetClient) QueryShares(_m *Snippet) *ShareQuery {
	query := (&ShareClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(snippet.Table, snippet.FieldID, id),
			sqlgraph.To(share.Table, share.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, snippet.SharesTable, snippet.SharesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SnippetClient) Hooks() []Hook {
	return c.hooks.Snippet
}

// Interceptors returns the client interceptors.
func (c *SnippetClient) Interceptors() []Interceptor {
	return c.inters.Snippet
}

func (c *SnippetClient) mutate(ctx context.Context, m *SnippetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SnippetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SnippetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SnippetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SnippetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Snippet mutation op: %q", m.Op())
	}
}

// SnippetAIMetadataClient is a client for the SnippetAIMetadata schema.
type SnippetAIMetadataClient struct {
	config
}

// NewSnippetAIMetadataClient returns a client for the SnippetAIMetadata from the given config.
func NewSnippetAIMetadataClient(c config) *SnippetAIMetadataClient {
	return &SnippetAIMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `snippetaimetadata.Hooks(f(g(h())))`.
func (c *SnippetAIMetadataClient) Use(hooks ...Hook) {
	c.hooks.SnippetAIMetadata = append(c.hooks.SnippetAIMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `snippetaimetadata.Intercept(f(g(h())))`.
func (c *SnippetAIMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.SnippetAIMetadata = append(c.inters.SnippetAIMetadata, interceptors...)
}

// Create returns a builder for creating a SnippetAIMetadata entity.
func (c *SnippetAIMetadataClient) Create() *SnippetAIMetadataCreate {
	mutation := newSnippetAIMetadataMutation(c.config, OpCreate)
	return &SnippetAIMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SnippetAIMetadata entities.
func (c *SnippetAIMetadataClient) CreateBulk(builders ...*SnippetAIMetadataCreate) *SnippetAIMetadataCreateBulk {
	return &SnippetAIMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SnippetAIMetadataClient) MapCreateBulk(slice any, setFunc func(*SnippetAIMetadataCreate, int)) *SnippetAIMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SnippetAIMetadataCreateBulk{err: fmt.Errorf("calling to SnippetAIMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SnippetAIMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SnippetAIMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SnippetAIMetadata.
func (c *SnippetAIMetadataClient) Update() *SnippetAIMetadataUpdate {
	mutation := newSnippetAIMetadataMutation(c.config, OpUpdate)
	return &SnippetAIMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SnippetAIMetadataClient) UpdateOne(_m *SnippetAIMetadata) *SnippetAIMetadataUpdateOne {
	mutation := newSnippetAIMetadataMutation(c.config, OpUpdateOne, withSnippetAIMetadata(_m))
	return &SnippetAIMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SnippetAIMetadataClient) UpdateOneID(id int64) *SnippetAIMetadataUpdateOne {
	mutation := newSnippetAIMetadataMutation(c.config, OpUpdateOne, withSnippetAIMetadataID(id))
	return &SnippetAIMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SnippetAIMetadata.
func (c *SnippetAIMetadataClient) Delete() *SnippetAIMetadataDelete {
	mutation := newSnippetAIMetadataMutation(c.config, OpDelete)
	return &SnippetAIMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SnippetAIMetadataClient) DeleteOne(_m *SnippetAIMetadata) *SnippetAIMetadataDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SnippetAIMetadataClient) DeleteOneID(id int64) *SnippetAIMetadataDeleteOne {
	builder := c.Delete().Where(snippetaimetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SnippetAIMetadataDeleteOne{builder}
}

// Query returns a query builder for SnippetAIMetadata.
func (c *SnippetAIMetadataClient) Query() *SnippetAIMetadataQuery {
	return &SnippetAIMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSnippetAIMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a SnippetAIMetadata entity by its id.
func (c *SnippetAIMetadataClient) Get(ctx context.Context, id int64) (*SnippetAIMetadata, error) {
	return c.Query().Where(snippetaimetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SnippetAIMetadataClient) GetX(ctx context.Context, id int64) *SnippetAIMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SnippetAIMetadataClient) Hooks() []Hook {
	return c.hooks.SnippetAIMetadata
}

// Interceptors returns the client interceptors.
func (c *SnippetAIMetadataClient) Interceptors() []Interceptor {
	return c.inters.SnippetAIMetadata
}

func (c *SnippetAIMetadataClient) mutate(ctx context.Context, m *SnippetAIMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SnippetAIMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SnippetAIMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SnippetAIMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SnippetAIMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SnippetAIMetadata mutation op: %q", m.Op())
	}
}

// SnippetLineageClient is a client for the SnippetLineage schema.
type SnippetLineageClient struct {
	config
}

// NewSnippetLineageClient returns a client for the SnippetLineage from the given config.
func NewSnippetLineageClient(c config) *SnippetLineageClient {
	return &SnippetLineageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `snippetlineage.Hooks(f(g(h())))`.
func (c *SnippetLineageClient) Use(hooks ...Hook) {
	c.hooks.SnippetLineage = append(c.hooks.SnippetLineage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `snippetlineage.Intercept(f(g(h())))`.
func (c *SnippetLineageClient) Intercept(interceptors ...Interceptor) {
	c.inters.SnippetLineage = append(c.inters.SnippetLineage, interceptors...)
}

// Create returns a builder for creating a SnippetLineage entity.
func (c *SnippetLineageClient) Create() *SnippetLineageCreate {
	mutation := newSnippetLineageMutation(c.config, OpCreate)
	return &SnippetLineageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SnippetLineage entities.
func (c *SnippetLineageClient) CreateBulk(builders ...*SnippetLineageCreate) *SnippetLineageCreateBulk {
	return &SnippetLineageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SnippetLineageClient) MapCreateBulk(slice any, setFunc func(*SnippetLineageCreate, int)) *SnippetLineageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SnippetLineageCreateBulk{err: fmt.Errorf("calling to SnippetLineageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SnippetLineageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SnippetLineageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SnippetLineage.
func (c *SnippetLineageClient) Update() *SnippetLineageUpdate {
	mutation := newSnippetLineageMutation(c.config, OpUpdate)
	return &SnippetLineageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SnippetLineageClient) UpdateOne(_m *SnippetLineage) *SnippetLineageUpdateOne {
	mutation := newSnippetLineageMutation(c.config, OpUpdateOne, withSnippetLineage(_m))
	return &SnippetLineageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SnippetLineageClient) UpdateOneID(id int64) *SnippetLineageUpdateOne {
	mutation := newSnippetLineageMutation(c.config, OpUpdateOne, withSnippetLineageID(id))
	return &SnippetLineageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SnippetLineage.
func (c *SnippetLineageClient) Delete() *SnippetLineageDelete {
	mutation := newSnippetLineageMutation(c.config, OpDelete)
	return &SnippetLineageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SnippetLineageClient) DeleteOne(_m *SnippetLineage) *SnippetLineageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SnippetLineageClient) DeleteOneID(id int64) *SnippetLineageDeleteOne {
	builder := c.Delete().Where(snippetlineage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SnippetLineageDeleteOne{builder}
}

// Query returns a query builder for SnippetLineage.
func (c *SnippetLineageClient) Query() *SnippetLineageQuery {
	return &SnippetLineageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSnippetLineage},
		inters: c.Interceptors(),
	}
}

// Get returns a SnippetLineage entity by its id.
func (c *SnippetLineageClient) Get(ctx context.Context, id int64) (*SnippetLineage, error) {
	return c.Query().Where(snippetlineage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SnippetLineageClient) GetX(ctx context.Context, id int64) *SnippetLineage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SnippetLineageClient) Hooks() []Hook {
	return c.hooks.SnippetLineage
}

// Interceptors returns the client interceptors.
func (c *SnippetLineageClient) Interceptors() []Interceptor {
	return c.inters.SnippetLineage
}

func (c *SnippetLineageClient) mutate(ctx context.Context, m *SnippetLineageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SnippetLineageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SnippetLineageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SnippetLineageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SnippetLineageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SnippetLineage mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int64) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id int64) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int64) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int64) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySnippets queries the snippets edge of a Tag.
func (c *TagClient) QuerySnippets(_m *Tag) *SnippetQuery {
	query := (&SnippetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(snippet.Table, snippet.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.SnippetsTable, tag.SnippetsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// TemplateClient is a client for the Template schema.
type TemplateClient struct {
	config
}

// NewTemplateClient returns a client for the Template from the given config.
func NewTemplateClient(c config) *TemplateClient {
	return &TemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `template.Hooks(f(g(h())))`.
func (c *TemplateClient) Use(hooks ...Hook) {
	c.hooks.Template = append(c.hooks.Template, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `template.Intercept(f(g(h())))`.
func (c *TemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.Template = append(c.inters.Template, interceptors...)
}

// Create returns a builder for creating a Template entity.
func (c *TemplateClient) Create() *TemplateCreate {
	mutation := newTemplateMutation(c.config, OpCreate)
	return &TemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Template entities.
func (c *TemplateClient) CreateBulk(builders ...*TemplateCreate) *TemplateCreateBulk {
	return &TemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TemplateClient) MapCreateBulk(slice any, setFunc func(*TemplateCreate, int)) *TemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TemplateCreateBulk{err: fmt.Errorf("calling to TemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Template.
func (c *TemplateClient) Update() *TemplateUpdate {
	mutation := newTemplateMutation(c.config, OpUpdate)
	return &TemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TemplateClient) UpdateOne(_m *Template) *TemplateUpdateOne {
	mutation := newTemplateMutation(c.config, OpUpdateOne, withTemplate(_m))
	return &TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TemplateClient) UpdateOneID(id int64) *TemplateUpdateOne {
	mutation := newTemplateMutation(c.config, OpUpdateOne, withTemplateID(id))
	return &TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Template.
func (c *TemplateClient) Delete() *TemplateDelete {
	mutation := newTemplateMutation(c.config, OpDelete)
	return &TemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TemplateClient) DeleteOne(_m *Template) *TemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TemplateClient) DeleteOneID(id int64) *TemplateDeleteOne {
	builder := c.Delete().Where(template.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TemplateDeleteOne{builder}
}

// Query returns a query builder for Template.
func (c *TemplateClient) Query() *TemplateQuery {
	return &TemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a Template entity by its id.
func (c *TemplateClient) Get(ctx context.Context, id int64) (*Template, error) {
	return c.Query().Where(template.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TemplateClient) GetX(ctx context.Context, id int64) *Template {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TemplateClient) Hooks() []Hook {
	return c.hooks.Template
}

// Interceptors returns the client interceptors.
func (c *TemplateClient) Interceptors() []Interceptor {
	return c.inters.Template
}

func (c *TemplateClient) mutate(ctx context.Context, m *TemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Template mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AICallLog, AIUsageDaily, Group, Share, Snippet, SnippetAIMetadata,
		SnippetLineage, Tag, Template []ent.Hook
	}
	inters struct {
		AICallLog, AIUsageDaily, Group, Share, Snippet, SnippetAIMetadata,
		SnippetLineage, Tag, Template []ent.Interceptor
	}
)
