// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/luckysxx/go-note/internal/ent/paste"
	"github.com/luckysxx/go-note/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pasteFields := schema.Paste{}.Fields()
	_ = pasteFields
	// pasteDescOwnerID is the schema descriptor for owner_id field.
	pasteDescOwnerID := pasteFields[1].Descriptor()
	// paste.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	paste.OwnerIDValidator = pasteDescOwnerID.Validators[0].(func(int64) error)
	// pasteDescTitle is the schema descriptor for title field.
	pasteDescTitle := pasteFields[2].Descriptor()
	// paste.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	paste.TitleValidator = func() func(string) error {
		validators := pasteDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pasteDescShortLink is the schema descriptor for short_link field.
	pasteDescShortLink := pasteFields[3].Descriptor()
	// paste.ShortLinkValidator is a validator for the "short_link" field. It is called by the builders before save.
	paste.ShortLinkValidator = pasteDescShortLink.Validators[0].(func(string) error)
	// pasteDescContent is the schema descriptor for content field.
	pasteDescContent := pasteFields[4].Descriptor()
	// paste.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	paste.ContentValidator = pasteDescContent.Validators[0].(func(string) error)
	// pasteDescLanguage is the schema descriptor for language field.
	pasteDescLanguage := pasteFields[5].Descriptor()
	// paste.DefaultLanguage holds the default value on creation for the language field.
	paste.DefaultLanguage = pasteDescLanguage.Default.(string)
	// paste.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	paste.LanguageValidator = pasteDescLanguage.Validators[0].(func(string) error)
	// pasteDescCreatedAt is the schema descriptor for created_at field.
	pasteDescCreatedAt := pasteFields[7].Descriptor()
	// paste.DefaultCreatedAt holds the default value on creation for the created_at field.
	paste.DefaultCreatedAt = pasteDescCreatedAt.Default.(func() time.Time)
	// pasteDescUpdatedAt is the schema descriptor for updated_at field.
	pasteDescUpdatedAt := pasteFields[8].Descriptor()
	// paste.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paste.DefaultUpdatedAt = pasteDescUpdatedAt.Default.(func() time.Time)
	// paste.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paste.UpdateDefaultUpdatedAt = pasteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pasteDescID is the schema descriptor for id field.
	pasteDescID := pasteFields[0].Descriptor()
	// paste.IDValidator is a validator for the "id" field. It is called by the builders before save.
	paste.IDValidator = pasteDescID.Validators[0].(func(int64) error)
}
