// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/share"
	"github.com/luckysxx/go-note/internal/ent/snippet"
)

// ShareCreate is the builder for creating a Share entity.
type ShareCreate struct {
	config
	mutation *ShareMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetToken sets the "token" field.
func (_c *ShareCreate) SetToken(v string) *ShareCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ShareCreate) SetKind(v share.Kind) *ShareCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *ShareCreate) SetNillableKind(v *share.Kind) *ShareCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetSnippetID sets the "snippet_id" field.
func (_c *ShareCreate) SetSnippetID(v int64) *ShareCreate {
	_c.mutation.SetSnippetID(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *ShareCreate) SetOwnerID(v int64) *ShareCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *ShareCreate) SetPasswordHash(v string) *ShareCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *ShareCreate) SetNillablePasswordHash(v *string) *ShareCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ShareCreate) SetExpiresAt(v time.Time) *ShareCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ShareCreate) SetNillableExpiresAt(v *time.Time) *ShareCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *ShareCreate) SetViewCount(v int) *ShareCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *ShareCreate) SetNillableViewCount(v *int) *ShareCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetForkCount sets the "fork_count" field.
func (_c *ShareCreate) SetForkCount(v int) *ShareCreate {
	_c.mutation.SetForkCount(v)
	return _c
}

// SetNillableForkCount sets the "fork_count" field if the given value is not nil.
func (_c *ShareCreate) SetNillableForkCount(v *int) *ShareCreate {
	if v != nil {
		_c.SetForkCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShareCreate) SetCreatedAt(v time.Time) *ShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShareCreate) SetNillableCreatedAt(v *time.Time) *ShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShareCreate) SetID(v int64) *ShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSnippet sets the "snippet" edge to the Snippet entity.
func (_c *ShareCreate) SetSnippet(v *Snippet) *ShareCreate {
	return _c.SetSnippetID(v.ID)
}

// Mutation returns the ShareMutation object of the builder.
func (_c *ShareCreate) Mutation() *ShareMutation {
	return _c.mutation
}

// Save creates the Share in the database.
func (_c *ShareCreate) Save(ctx context.Context) (*Share, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShareCreate) SaveX(ctx context.Context) *Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShareCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := share.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := share.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.ForkCount(); !ok {
		v := share.DefaultForkCount
		_c.mutation.SetForkCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := share.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShareCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Share.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := share.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Share.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Share.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := share.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Share.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnippetID(); !ok {
		return &ValidationError{Name: "snippet_id", err: errors.New(`ent: missing required field "Share.snippet_id"`)}
	}
	if v, ok := _c.mutation.SnippetID(); ok {
		if err := share.SnippetIDValidator(v); err != nil {
			return &ValidationError{Name: "snippet_id", err: fmt.Errorf(`ent: validator failed for field "Share.snippet_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Share.owner_id"`)}
	}
	if v, ok := _c.mutation.OwnerID(); ok {
		if err := share.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Share.owner_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := share.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Share.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Share.view_count"`)}
	}
	if _, ok := _c.mutation.ForkCount(); !ok {
		return &ValidationError{Name: "fork_count", err: errors.New(`ent: missing required field "Share.fork_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Share.created_at"`)}
	}
	if len(_c.mutation.SnippetIDs()) == 0 {
		return &ValidationError{Name: "snippet", err: errors.New(`ent: missing required edge "Share.snippet"`)}
	}
	return nil
}

func (_c *ShareCreate) sqlSave(ctx context.Context) (*Share, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShareCreate) createSpec() (*Share, *sqlgraph.CreateSpec) {
	var (
		_node = &Share{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(share.Table, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(share.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(share.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(share.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(share.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(share.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.ForkCount(); ok {
		_spec.SetField(share.FieldForkCount, field.TypeInt, value)
		_node.ForkCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SnippetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.SnippetTable,
			Columns: []string{share.SnippetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snippet.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SnippetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Share.Create().
//		SetToken(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShareUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ShareCreate) OnConflict(opts ...sql.ConflictOption) *ShareUpsertOne {
	_c.conflict = opts
	return &ShareUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Share.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShareCreate) OnConflictColumns(columns ...string) *ShareUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShareUpsertOne{
		create: _c,
	}
}

type (
	// ShareUpsertOne is the builder for "upsert"-ing
	//  one Share node.
	ShareUpsertOne struct {
		create *ShareCreate
	}

	// ShareUpsert is the "OnConflict" setter.
	ShareUpsert struct {
		*sql.UpdateSet
	}
)

// SetToken sets the "token" field.
func (u *ShareUpsert) SetToken(v string) *ShareUpsert {
	u.Set(share.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ShareUpsert) UpdateToken() *ShareUpsert {
	u.SetExcluded(share.FieldToken)
	return u
}

// SetKind sets the "kind" field.
func (u *ShareUpsert) SetKind(v share.Kind) *ShareUpsert {
	u.Set(share.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ShareUpsert) UpdateKind() *ShareUpsert {
	u.SetExcluded(share.FieldKind)
	return u
}

// SetSnippetID sets the "snippet_id" field.
func (u *ShareUpsert) SetSnippetID(v int64) *ShareUpsert {
	u.Set(share.FieldSnippetID, v)
	return u
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *ShareUpsert) UpdateSnippetID() *ShareUpsert {
	u.SetExcluded(share.FieldSnippetID)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *ShareUpsert) SetOwnerID(v int64) *ShareUpsert {
	u.Set(share.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *ShareUpsert) UpdateOwnerID() *ShareUpsert {
	u.SetExcluded(share.FieldOwnerID)
	return u
}

// AddOwnerID adds v to the "owner_id" field.
func (u *ShareUpsert) AddOwnerID(v int64) *ShareUpsert {
	u.Add(share.FieldOwnerID, v)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *ShareUpsert) SetPasswordHash(v string) *ShareUpsert {
	u.Set(share.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *ShareUpsert) UpdatePasswordHash() *ShareUpsert {
	u.SetExcluded(share.FieldPasswordHash)
	return u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (u *ShareUpsert) ClearPasswordHash() *ShareUpsert {
	u.SetNull(share.FieldPasswordHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ShareUpsert) SetExpiresAt(v time.Time) *ShareUpsert {
	u.Set(share.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ShareUpsert) UpdateExpiresAt() *ShareUpsert {
	u.SetExcluded(share.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ShareUpsert) ClearExpiresAt() *ShareUpsert {
	u.SetNull(share.FieldExpiresAt)
	return u
}

// SetViewCount sets the "view_count" field.
func (u *ShareUpsert) SetViewCount(v int) *ShareUpsert {
	u.Set(share.FieldViewCount, v)
	return u
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *ShareUpsert) UpdateViewCount() *ShareUpsert {
	u.SetExcluded(share.FieldViewCount)
	return u
}

// AddViewCount adds v to the "view_count" field.
func (u *ShareUpsert) AddViewCount(v int) *ShareUpsert {
	u.Add(share.FieldViewCount, v)
	return u
}

// SetForkCount sets the "fork_count" field.
func (u *ShareUpsert) SetForkCount(v int) *ShareUpsert {
	u.Set(share.FieldForkCount, v)
	return u
}

// UpdateForkCount sets the "fork_count" field to the value that was provided on create.
func (u *ShareUpsert) UpdateForkCount() *ShareUpsert {
	u.SetExcluded(share.FieldForkCount)
	return u
}

// AddForkCount adds v to the "fork_count" field.
func (u *ShareUpsert) AddForkCount(v int) *ShareUpsert {
	u.Add(share.FieldForkCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Share.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(share.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShareUpsertOne) UpdateNewValues() *ShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(share.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(share.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Share.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShareUpsertOne) Ignore() *ShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShareUpsertOne) DoNothing() *ShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShareCreate.OnConflict
// documentation for more info.
func (u *ShareUpsertOne) Update(set func(*ShareUpsert)) *ShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *ShareUpsertOne) SetToken(v string) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateToken() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateToken()
	})
}

// SetKind sets the "kind" field.
func (u *ShareUpsertOne) SetKind(v share.Kind) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateKind() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateKind()
	})
}

// SetSnippetID sets the "snippet_id" field.
func (u *ShareUpsertOne) SetSnippetID(v int64) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetSnippetID(v)
	})
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateSnippetID() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateSnippetID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *ShareUpsertOne) SetOwnerID(v int64) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *ShareUpsertOne) AddOwnerID(v int64) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateOwnerID() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateOwnerID()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *ShareUpsertOne) SetPasswordHash(v string) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdatePasswordHash() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdatePasswordHash()
	})
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (u *ShareUpsertOne) ClearPasswordHash() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.ClearPasswordHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ShareUpsertOne) SetExpiresAt(v time.Time) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateExpiresAt() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ShareUpsertOne) ClearExpiresAt() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.ClearExpiresAt()
	})
}

// SetViewCount sets the "view_count" field.
func (u *ShareUpsertOne) SetViewCount(v int) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *ShareUpsertOne) AddViewCount(v int) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateViewCount() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateViewCount()
	})
}

// SetForkCount sets the "fork_count" field.
func (u *ShareUpsertOne) SetForkCount(v int) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.SetForkCount(v)
	})
}

// AddForkCount adds v to the "fork_count" field.
func (u *ShareUpsertOne) AddForkCount(v int) *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.AddForkCount(v)
	})
}

// UpdateForkCount sets the "fork_count" field to the value that was provided on create.
func (u *ShareUpsertOne) UpdateForkCount() *ShareUpsertOne {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateForkCount()
	})
}

// Exec executes the query.
func (u *ShareUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShareCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShareUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShareUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShareUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShareCreateBulk is the builder for creating many Share entities in bulk.
type ShareCreateBulk struct {
	config
	err      error
	builders []*ShareCreate
	conflict []sql.ConflictOption
}

// Save creates the Share entities in the database.
func (_c *ShareCreateBulk) Save(ctx context.Context) ([]*Share, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Share, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShareCreateBulk) SaveX(ctx context.Context) []*Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Share.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShareUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *ShareCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShareUpsertBulk {
	_c.conflict = opts
	return &ShareUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Share.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShareCreateBulk) OnConflictColumns(columns ...string) *ShareUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShareUpsertBulk{
		create: _c,
	}
}

// ShareUpsertBulk is the builder for "upsert"-ing
// a bulk of Share nodes.
type ShareUpsertBulk struct {
	create *ShareCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Share.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(share.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShareUpsertBulk) UpdateNewValues() *ShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(share.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(share.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Share.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShareUpsertBulk) Ignore() *ShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShareUpsertBulk) DoNothing() *ShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShareCreateBulk.OnConflict
// documentation for more info.
func (u *ShareUpsertBulk) Update(set func(*ShareUpsert)) *ShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *ShareUpsertBulk) SetToken(v string) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateToken() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateToken()
	})
}

// SetKind sets the "kind" field.
func (u *ShareUpsertBulk) SetKind(v share.Kind) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateKind() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateKind()
	})
}

// SetSnippetID sets the "snippet_id" field.
func (u *ShareUpsertBulk) SetSnippetID(v int64) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetSnippetID(v)
	})
}

// UpdateSnippetID sets the "snippet_id" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateSnippetID() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateSnippetID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *ShareUpsertBulk) SetOwnerID(v int64) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *ShareUpsertBulk) AddOwnerID(v int64) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateOwnerID() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateOwnerID()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *ShareUpsertBulk) SetPasswordHash(v string) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdatePasswordHash() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdatePasswordHash()
	})
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (u *ShareUpsertBulk) ClearPasswordHash() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.ClearPasswordHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ShareUpsertBulk) SetExpiresAt(v time.Time) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateExpiresAt() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ShareUpsertBulk) ClearExpiresAt() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.ClearExpiresAt()
	})
}

// SetViewCount sets the "view_count" field.
func (u *ShareUpsertBulk) SetViewCount(v int) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *ShareUpsertBulk) AddViewCount(v int) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateViewCount() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateViewCount()
	})
}

// SetForkCount sets the "fork_count" field.
func (u *ShareUpsertBulk) SetForkCount(v int) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.SetForkCount(v)
	})
}

// AddForkCount adds v to the "fork_count" field.
func (u *ShareUpsertBulk) AddForkCount(v int) *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.AddForkCount(v)
	})
}

// UpdateForkCount sets the "fork_count" field to the value that was provided on create.
func (u *ShareUpsertBulk) UpdateForkCount() *ShareUpsertBulk {
	return u.Update(func(s *ShareUpsert) {
		s.UpdateForkCount()
	})
}

// Exec executes the query.
func (u *ShareUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShareCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShareCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShareUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
