// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/predicate"
	"github.com/luckysxx/go-note/internal/ent/snippetaimetadata"
)

// SnippetAIMetadataDelete is the builder for deleting a SnippetAIMetadata entity.
type SnippetAIMetadataDelete struct {
	config
	hooks    []Hook
	mutation *SnippetAIMetadataMutation
}

// Where appends a list predicates to the SnippetAIMetadataDelete builder.
func (_d *SnippetAIMetadataDelete) Where(ps ...predicate.SnippetAIMetadata) *SnippetAIMetadataDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SnippetAIMetadataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SnippetAIMetadataDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SnippetAIMetadataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(snippetaimetadata.Table, sqlgraph.NewFieldSpec(snippetaimetadata.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SnippetAIMetadataDeleteOne is the builder for deleting a single SnippetAIMetadata entity.
type SnippetAIMetadataDeleteOne struct {
	_d *SnippetAIMetadataDelete
}

// Where appends a list predicates to the SnippetAIMetadataDelete builder.
func (_d *SnippetAIMetadataDeleteOne) Where(ps ...predicate.SnippetAIMetadata) *SnippetAIMetadataDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SnippetAIMetadataDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{snippetaimetadata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SnippetAIMetadataDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
