// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/go-note/internal/ent/snippetlineage"
)

// SnippetLineage is the model entity for the SnippetLineage schema.
type SnippetLineage struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的全局唯一 ID
	ID int64 `json:"id,omitempty"`
	// 当前文档 ID
	SnippetID int64 `json:"snippet_id,omitempty"`
	// 来源文档 ID
	SourceSnippetID *int64 `json:"source_snippet_id,omitempty"`
	// 来源分享 ID
	SourceShareID *int64 `json:"source_share_id,omitempty"`
	// 来源作者 ID
	SourceUserID *int64 `json:"source_user_id,omitempty"`
	// 来源关系类型
	RelationType snippetlineage.RelationType `json:"relation_type,omitempty"`
	// 创建时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SnippetLineage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case snippetlineage.FieldID, snippetlineage.FieldSnippetID, snippetlineage.FieldSourceSnippetID, snippetlineage.FieldSourceShareID, snippetlineage.FieldSourceUserID:
			values[i] = new(sql.NullInt64)
		case snippetlineage.FieldRelationType:
			values[i] = new(sql.NullString)
		case snippetlineage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SnippetLineage fields.
func (_m *SnippetLineage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case snippetlineage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case snippetlineage.FieldSnippetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field snippet_id", values[i])
			} else if value.Valid {
				_m.SnippetID = value.Int64
			}
		case snippetlineage.FieldSourceSnippetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_snippet_id", values[i])
			} else if value.Valid {
				_m.SourceSnippetID = new(int64)
				*_m.SourceSnippetID = value.Int64
			}
		case snippetlineage.FieldSourceShareID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_share_id", values[i])
			} else if value.Valid {
				_m.SourceShareID = new(int64)
				*_m.SourceShareID = value.Int64
			}
		case snippetlineage.FieldSourceUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_user_id", values[i])
			} else if value.Valid {
				_m.SourceUserID = new(int64)
				*_m.SourceUserID = value.Int64
			}
		case snippetlineage.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				_m.RelationType = snippetlineage.RelationType(value.String)
			}
		case snippetlineage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SnippetLineage.
// This includes values selected through modifiers, order, etc.
func (_m *SnippetLineage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SnippetLineage.
// Note that you need to call SnippetLineage.Unwrap() before calling this method if this SnippetLineage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SnippetLineage) Update() *SnippetLineageUpdateOne {
	return NewSnippetLineageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SnippetLineage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SnippetLineage) Unwrap() *SnippetLineage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SnippetLineage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SnippetLineage) String() string {
	var builder strings.Builder
	builder.WriteString("SnippetLineage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("snippet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnippetID))
	builder.WriteString(", ")
	if v := _m.SourceSnippetID; v != nil {
		builder.WriteString("source_snippet_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceShareID; v != nil {
		builder.WriteString("source_share_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceUserID; v != nil {
		builder.WriteString("source_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("relation_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelationType))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SnippetLineages is a parsable slice of SnippetLineage.
type SnippetLineages []*SnippetLineage
