// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/predicate"
	"github.com/luckysxx/go-note/internal/ent/snippetaimetadata"
)

// SnippetAIMetadataUpdate is the builder for updating SnippetAIMetadata entities.
type SnippetAIMetadataUpdate struct {
	config
	hooks    []Hook
	mutation *SnippetAIMetadataMutation
}

// Where appends a list predicates to the SnippetAIMetadataUpdate builder.
func (_u *SnippetAIMetadataUpdate) Where(ps ...predicate.SnippetAIMetadata) *SnippetAIMetadataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *SnippetAIMetadataUpdate) SetOwnerID(v int64) *SnippetAIMetadataUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdate) SetNillableOwnerID(v *int64) *SnippetAIMetadataUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *SnippetAIMetadataUpdate) AddOwnerID(v int64) *SnippetAIMetadataUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SnippetAIMetadataUpdate) SetSummary(v string) *SnippetAIMetadataUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdate) SetNillableSummary(v *string) *SnippetAIMetadataUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SnippetAIMetadataUpdate) ClearSummary() *SnippetAIMetadataUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetSuggestedTags sets the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdate) SetSuggestedTags(v []string) *SnippetAIMetadataUpdate {
	_u.mutation.SetSuggestedTags(v)
	return _u
}

// AppendSuggestedTags appends value to the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdate) AppendSuggestedTags(v []string) *SnippetAIMetadataUpdate {
	_u.mutation.AppendSuggestedTags(v)
	return _u
}

// ClearSuggestedTags clears the value of the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdate) ClearSuggestedTags() *SnippetAIMetadataUpdate {
	_u.mutation.ClearSuggestedTags()
	return _u
}

// SetExtractedTodos sets the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdate) SetExtractedTodos(v []map[string]interface{}) *SnippetAIMetadataUpdate {
	_u.mutation.SetExtractedTodos(v)
	return _u
}

// AppendExtractedTodos appends value to the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdate) AppendExtractedTodos(v []map[string]interface{}) *SnippetAIMetadataUpdate {
	_u.mutation.AppendExtractedTodos(v)
	return _u
}

// ClearExtractedTodos clears the value of the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdate) ClearExtractedTodos() *SnippetAIMetadataUpdate {
	_u.mutation.ClearExtractedTodos()
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *SnippetAIMetadataUpdate) SetContentHash(v uint32) *SnippetAIMetadataUpdate {
	_u.mutation.ResetContentHash()
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdate) SetNillableContentHash(v *uint32) *SnippetAIMetadataUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// AddContentHash adds value to the "content_hash" field.
func (_u *SnippetAIMetadataUpdate) AddContentHash(v int32) *SnippetAIMetadataUpdate {
	_u.mutation.AddContentHash(v)
	return _u
}

// SetPromptVersion sets the "prompt_version" field.
func (_u *SnippetAIMetadataUpdate) SetPromptVersion(v string) *SnippetAIMetadataUpdate {
	_u.mutation.SetPromptVersion(v)
	return _u
}

// SetNillablePromptVersion sets the "prompt_version" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdate) SetNillablePromptVersion(v *string) *SnippetAIMetadataUpdate {
	if v != nil {
		_u.SetPromptVersion(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SnippetAIMetadataUpdate) SetModel(v string) *SnippetAIMetadataUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdate) SetNillableModel(v *string) *SnippetAIMetadataUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SnippetAIMetadataUpdate) ClearModel() *SnippetAIMetadataUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SnippetAIMetadataUpdate) SetUpdatedAt(v time.Time) *SnippetAIMetadataUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SnippetAIMetadataMutation object of the builder.
func (_u *SnippetAIMetadataUpdate) Mutation() *SnippetAIMetadataMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SnippetAIMetadataUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnippetAIMetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SnippetAIMetadataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnippetAIMetadataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SnippetAIMetadataUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := snippetaimetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SnippetAIMetadataUpdate) check() error {
	if v, ok := _u.mutation.PromptVersion(); ok {
		if err := snippetaimetadata.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "SnippetAIMetadata.prompt_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := snippetaimetadata.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SnippetAIMetadata.model": %w`, err)}
		}
	}
	return nil
}

func (_u *SnippetAIMetadataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snippetaimetadata.Table, snippetaimetadata.Columns, sqlgraph.NewFieldSpec(snippetaimetadata.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(snippetaimetadata.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(snippetaimetadata.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(snippetaimetadata.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(snippetaimetadata.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.SuggestedTags(); ok {
		_spec.SetField(snippetaimetadata.FieldSuggestedTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSuggestedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snippetaimetadata.FieldSuggestedTags, value)
		})
	}
	if _u.mutation.SuggestedTagsCleared() {
		_spec.ClearField(snippetaimetadata.FieldSuggestedTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExtractedTodos(); ok {
		_spec.SetField(snippetaimetadata.FieldExtractedTodos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtractedTodos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snippetaimetadata.FieldExtractedTodos, value)
		})
	}
	if _u.mutation.ExtractedTodosCleared() {
		_spec.ClearField(snippetaimetadata.FieldExtractedTodos, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(snippetaimetadata.FieldContentHash, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedContentHash(); ok {
		_spec.AddField(snippetaimetadata.FieldContentHash, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PromptVersion(); ok {
		_spec.SetField(snippetaimetadata.FieldPromptVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(snippetaimetadata.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(snippetaimetadata.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(snippetaimetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snippetaimetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SnippetAIMetadataUpdateOne is the builder for updating a single SnippetAIMetadata entity.
type SnippetAIMetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SnippetAIMetadataMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *SnippetAIMetadataUpdateOne) SetOwnerID(v int64) *SnippetAIMetadataUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdateOne) SetNillableOwnerID(v *int64) *SnippetAIMetadataUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *SnippetAIMetadataUpdateOne) AddOwnerID(v int64) *SnippetAIMetadataUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SnippetAIMetadataUpdateOne) SetSummary(v string) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdateOne) SetNillableSummary(v *string) *SnippetAIMetadataUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SnippetAIMetadataUpdateOne) ClearSummary() *SnippetAIMetadataUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetSuggestedTags sets the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdateOne) SetSuggestedTags(v []string) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetSuggestedTags(v)
	return _u
}

// AppendSuggestedTags appends value to the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdateOne) AppendSuggestedTags(v []string) *SnippetAIMetadataUpdateOne {
	_u.mutation.AppendSuggestedTags(v)
	return _u
}

// ClearSuggestedTags clears the value of the "suggested_tags" field.
func (_u *SnippetAIMetadataUpdateOne) ClearSuggestedTags() *SnippetAIMetadataUpdateOne {
	_u.mutation.ClearSuggestedTags()
	return _u
}

// SetExtractedTodos sets the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdateOne) SetExtractedTodos(v []map[string]interface{}) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetExtractedTodos(v)
	return _u
}

// AppendExtractedTodos appends value to the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdateOne) AppendExtractedTodos(v []map[string]interface{}) *SnippetAIMetadataUpdateOne {
	_u.mutation.AppendExtractedTodos(v)
	return _u
}

// ClearExtractedTodos clears the value of the "extracted_todos" field.
func (_u *SnippetAIMetadataUpdateOne) ClearExtractedTodos() *SnippetAIMetadataUpdateOne {
	_u.mutation.ClearExtractedTodos()
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *SnippetAIMetadataUpdateOne) SetContentHash(v uint32) *SnippetAIMetadataUpdateOne {
	_u.mutation.ResetContentHash()
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdateOne) SetNillableContentHash(v *uint32) *SnippetAIMetadataUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// AddContentHash adds value to the "content_hash" field.
func (_u *SnippetAIMetadataUpdateOne) AddContentHash(v int32) *SnippetAIMetadataUpdateOne {
	_u.mutation.AddContentHash(v)
	return _u
}

// SetPromptVersion sets the "prompt_version" field.
func (_u *SnippetAIMetadataUpdateOne) SetPromptVersion(v string) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetPromptVersion(v)
	return _u
}

// SetNillablePromptVersion sets the "prompt_version" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdateOne) SetNillablePromptVersion(v *string) *SnippetAIMetadataUpdateOne {
	if v != nil {
		_u.SetPromptVersion(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *SnippetAIMetadataUpdateOne) SetModel(v string) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SnippetAIMetadataUpdateOne) SetNillableModel(v *string) *SnippetAIMetadataUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SnippetAIMetadataUpdateOne) ClearModel() *SnippetAIMetadataUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SnippetAIMetadataUpdateOne) SetUpdatedAt(v time.Time) *SnippetAIMetadataUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SnippetAIMetadataMutation object of the builder.
func (_u *SnippetAIMetadataUpdateOne) Mutation() *SnippetAIMetadataMutation {
	return _u.mutation
}

// Where appends a list predicates to the SnippetAIMetadataUpdate builder.
func (_u *SnippetAIMetadataUpdateOne) Where(ps ...predicate.SnippetAIMetadata) *SnippetAIMetadataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SnippetAIMetadataUpdateOne) Select(field string, fields ...string) *SnippetAIMetadataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SnippetAIMetadata entity.
func (_u *SnippetAIMetadataUpdateOne) Save(ctx context.Context) (*SnippetAIMetadata, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnippetAIMetadataUpdateOne) SaveX(ctx context.Context) *SnippetAIMetadata {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SnippetAIMetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnippetAIMetadataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SnippetAIMetadataUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := snippetaimetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SnippetAIMetadataUpdateOne) check() error {
	if v, ok := _u.mutation.PromptVersion(); ok {
		if err := snippetaimetadata.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "SnippetAIMetadata.prompt_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := snippetaimetadata.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SnippetAIMetadata.model": %w`, err)}
		}
	}
	return nil
}

func (_u *SnippetAIMetadataUpdateOne) sqlSave(ctx context.Context) (_node *SnippetAIMetadata, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snippetaimetadata.Table, snippetaimetadata.Columns, sqlgraph.NewFieldSpec(snippetaimetadata.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SnippetAIMetadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snippetaimetadata.FieldID)
		for _, f := range fields {
			if !snippetaimetadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snippetaimetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(snippetaimetadata.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(snippetaimetadata.FieldOwnerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(snippetaimetadata.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(snippetaimetadata.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.SuggestedTags(); ok {
		_spec.SetField(snippetaimetadata.FieldSuggestedTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSuggestedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snippetaimetadata.FieldSuggestedTags, value)
		})
	}
	if _u.mutation.SuggestedTagsCleared() {
		_spec.ClearField(snippetaimetadata.FieldSuggestedTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExtractedTodos(); ok {
		_spec.SetField(snippetaimetadata.FieldExtractedTodos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtractedTodos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snippetaimetadata.FieldExtractedTodos, value)
		})
	}
	if _u.mutation.ExtractedTodosCleared() {
		_spec.ClearField(snippetaimetadata.FieldExtractedTodos, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(snippetaimetadata.FieldContentHash, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedContentHash(); ok {
		_spec.AddField(snippetaimetadata.FieldContentHash, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PromptVersion(); ok {
		_spec.SetField(snippetaimetadata.FieldPromptVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(snippetaimetadata.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(snippetaimetadata.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(snippetaimetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SnippetAIMetadata{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snippetaimetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
