// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/go-note/internal/ent/group"
	"github.com/luckysxx/go-note/internal/ent/snippet"
)

// Snippet is the model entity for the Snippet schema.
type Snippet struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的全局唯一 ID
	ID int64 `json:"id,omitempty"`
	// 关联的用户 ID
	OwnerID int64 `json:"owner_id,omitempty"`
	// 内容类型：code=代码片段 note=笔记 file=文件上传
	Type snippet.Type `json:"type,omitempty"`
	// 标题
	Title string `json:"title,omitempty"`
	// 代码或笔记的文本内容
	Content string `json:"content,omitempty"`
	// 文件的对象存储路径
	FileURL string `json:"file_url,omitempty"`
	// 文件大小（字节）
	FileSize int64 `json:"file_size,omitempty"`
	// 文件 MIME 类型
	MimeType string `json:"mime_type,omitempty"`
	// 编程语言或文件类型标识
	Language string `json:"language,omitempty"`
	// 可见性：public=公开 private=私有
	Visibility snippet.Visibility `json:"visibility,omitempty"`
	// 所属分组 ID
	GroupID *int64 `json:"group_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SnippetQuery when eager-loading is set.
	Edges        SnippetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SnippetEdges holds the relations/edges for other nodes in the graph.
type SnippetEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SnippetEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e SnippetEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Snippet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case snippet.FieldID, snippet.FieldOwnerID, snippet.FieldFileSize, snippet.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case snippet.FieldType, snippet.FieldTitle, snippet.FieldContent, snippet.FieldFileURL, snippet.FieldMimeType, snippet.FieldLanguage, snippet.FieldVisibility:
			values[i] = new(sql.NullString)
		case snippet.FieldCreatedAt, snippet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Snippet fields.
func (_m *Snippet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case snippet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case snippet.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.Int64
			}
		case snippet.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = snippet.Type(value.String)
			}
		case snippet.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case snippet.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case snippet.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				_m.FileURL = value.String
			}
		case snippet.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case snippet.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case snippet.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case snippet.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = snippet.Visibility(value.String)
			}
		case snippet.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case snippet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case snippet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Snippet.
// This includes values selected through modifiers, order, etc.
func (_m *Snippet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Snippet entity.
func (_m *Snippet) QueryGroup() *GroupQuery {
	return NewSnippetClient(_m.config).QueryGroup(_m)
}

// QueryTags queries the "tags" edge of the Snippet entity.
func (_m *Snippet) QueryTags() *TagQuery {
	return NewSnippetClient(_m.config).QueryTags(_m)
}

// Update returns a builder for updating this Snippet.
// Note that you need to call Snippet.Unwrap() before calling this method if this Snippet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Snippet) Update() *SnippetUpdateOne {
	return NewSnippetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Snippet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Snippet) Unwrap() *Snippet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Snippet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Snippet) String() string {
	var builder strings.Builder
	builder.WriteString("Snippet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(_m.FileURL)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Snippets is a parsable slice of Snippet.
type Snippets []*Snippet
