// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/go-note/internal/ent/template"
)

// TemplateCreate is the builder for creating a Template entity.
type TemplateCreate struct {
	config
	mutation *TemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwnerID sets the "owner_id" field.
func (_c *TemplateCreate) SetOwnerID(v int64) *TemplateCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableOwnerID(v *int64) *TemplateCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TemplateCreate) SetName(v string) *TemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TemplateCreate) SetDescription(v string) *TemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableDescription(v *string) *TemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *TemplateCreate) SetContent(v string) *TemplateCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *TemplateCreate) SetLanguage(v string) *TemplateCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableLanguage(v *string) *TemplateCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *TemplateCreate) SetCategory(v string) *TemplateCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableCategory(v *string) *TemplateCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *TemplateCreate) SetIsSystem(v bool) *TemplateCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableIsSystem(v *bool) *TemplateCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TemplateCreate) SetCreatedAt(v time.Time) *TemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableCreatedAt(v *time.Time) *TemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TemplateCreate) SetUpdatedAt(v time.Time) *TemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableUpdatedAt(v *time.Time) *TemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TemplateCreate) SetID(v int64) *TemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TemplateMutation object of the builder.
func (_c *TemplateCreate) Mutation() *TemplateMutation {
	return _c.mutation
}

// Save creates the Template in the database.
func (_c *TemplateCreate) Save(ctx context.Context) (*Template, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateCreate) SaveX(ctx context.Context) *Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemplateCreate) defaults() {
	if _, ok := _c.mutation.OwnerID(); !ok {
		v := template.DefaultOwnerID
		_c.mutation.SetOwnerID(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := template.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := template.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := template.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := template.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := template.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := template.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateCreate) check() error {
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Template.owner_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Template.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := template.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Template.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Template.content"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Template.language"`)}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := template.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Template.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Template.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := template.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Template.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Template.is_system"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Template.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Template.updated_at"`)}
	}
	return nil
}

func (_c *TemplateCreate) sqlSave(ctx context.Context) (*Template, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateCreate) createSpec() (*Template, *sqlgraph.CreateSpec) {
	var (
		_node = &Template{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(template.Table, sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(template.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(template.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(template.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(template.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(template.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(template.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.Create().
//		SetOwnerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *TemplateCreate) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertOne {
	_c.conflict = opts
	return &TemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemplateCreate) OnConflictColumns(columns ...string) *TemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertOne{
		create: _c,
	}
}

type (
	// TemplateUpsertOne is the builder for "upsert"-ing
	//  one Template node.
	TemplateUpsertOne struct {
		create *TemplateCreate
	}

	// TemplateUpsert is the "OnConflict" setter.
	TemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwnerID sets the "owner_id" field.
func (u *TemplateUpsert) SetOwnerID(v int64) *TemplateUpsert {
	u.Set(template.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateOwnerID() *TemplateUpsert {
	u.SetExcluded(template.FieldOwnerID)
	return u
}

// AddOwnerID adds v to the "owner_id" field.
func (u *TemplateUpsert) AddOwnerID(v int64) *TemplateUpsert {
	u.Add(template.FieldOwnerID, v)
	return u
}

// SetName sets the "name" field.
func (u *TemplateUpsert) SetName(v string) *TemplateUpsert {
	u.Set(template.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateName() *TemplateUpsert {
	u.SetExcluded(template.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TemplateUpsert) SetDescription(v string) *TemplateUpsert {
	u.Set(template.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateDescription() *TemplateUpsert {
	u.SetExcluded(template.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsert) ClearDescription() *TemplateUpsert {
	u.SetNull(template.FieldDescription)
	return u
}

// SetContent sets the "content" field.
func (u *TemplateUpsert) SetContent(v string) *TemplateUpsert {
	u.Set(template.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateContent() *TemplateUpsert {
	u.SetExcluded(template.FieldContent)
	return u
}

// SetLanguage sets the "language" field.
func (u *TemplateUpsert) SetLanguage(v string) *TemplateUpsert {
	u.Set(template.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateLanguage() *TemplateUpsert {
	u.SetExcluded(template.FieldLanguage)
	return u
}

// SetCategory sets the "category" field.
func (u *TemplateUpsert) SetCategory(v string) *TemplateUpsert {
	u.Set(template.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateCategory() *TemplateUpsert {
	u.SetExcluded(template.FieldCategory)
	return u
}

// SetIsSystem sets the "is_system" field.
func (u *TemplateUpsert) SetIsSystem(v bool) *TemplateUpsert {
	u.Set(template.FieldIsSystem, v)
	return u
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateIsSystem() *TemplateUpsert {
	u.SetExcluded(template.FieldIsSystem)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsert) SetUpdatedAt(v time.Time) *TemplateUpsert {
	u.Set(template.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateUpdatedAt() *TemplateUpsert {
	u.SetExcluded(template.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TemplateUpsertOne) UpdateNewValues() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(template.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(template.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TemplateUpsertOne) Ignore() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertOne) DoNothing() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreate.OnConflict
// documentation for more info.
func (u *TemplateUpsertOne) Update(set func(*TemplateUpsert)) *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *TemplateUpsertOne) SetOwnerID(v int64) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *TemplateUpsertOne) AddOwnerID(v int64) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateOwnerID() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateOwnerID()
	})
}

// SetName sets the "name" field.
func (u *TemplateUpsertOne) SetName(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateName() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TemplateUpsertOne) SetDescription(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateDescription() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsertOne) ClearDescription() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearDescription()
	})
}

// SetContent sets the "content" field.
func (u *TemplateUpsertOne) SetContent(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateContent() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateContent()
	})
}

// SetLanguage sets the "language" field.
func (u *TemplateUpsertOne) SetLanguage(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateLanguage() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateLanguage()
	})
}

// SetCategory sets the "category" field.
func (u *TemplateUpsertOne) SetCategory(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateCategory() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCategory()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *TemplateUpsertOne) SetIsSystem(v bool) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateIsSystem() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateIsSystem()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsertOne) SetUpdatedAt(v time.Time) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateUpdatedAt() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TemplateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TemplateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TemplateCreateBulk is the builder for creating many Template entities in bulk.
type TemplateCreateBulk struct {
	config
	err      error
	builders []*TemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the Template entities in the database.
func (_c *TemplateCreateBulk) Save(ctx context.Context) ([]*Template, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Template, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateCreateBulk) SaveX(ctx context.Context) []*Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *TemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertBulk {
	_c.conflict = opts
	return &TemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemplateCreateBulk) OnConflictColumns(columns ...string) *TemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertBulk{
		create: _c,
	}
}

// TemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of Template nodes.
type TemplateUpsertBulk struct {
	create *TemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TemplateUpsertBulk) UpdateNewValues() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(template.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(template.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TemplateUpsertBulk) Ignore() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertBulk) DoNothing() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreateBulk.OnConflict
// documentation for more info.
func (u *TemplateUpsertBulk) Update(set func(*TemplateUpsert)) *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *TemplateUpsertBulk) SetOwnerID(v int64) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *TemplateUpsertBulk) AddOwnerID(v int64) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateOwnerID() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateOwnerID()
	})
}

// SetName sets the "name" field.
func (u *TemplateUpsertBulk) SetName(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateName() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TemplateUpsertBulk) SetDescription(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateDescription() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsertBulk) ClearDescription() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearDescription()
	})
}

// SetContent sets the "content" field.
func (u *TemplateUpsertBulk) SetContent(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateContent() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateContent()
	})
}

// SetLanguage sets the "language" field.
func (u *TemplateUpsertBulk) SetLanguage(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateLanguage() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateLanguage()
	})
}

// SetCategory sets the "category" field.
func (u *TemplateUpsertBulk) SetCategory(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateCategory() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCategory()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *TemplateUpsertBulk) SetIsSystem(v bool) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateIsSystem() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateIsSystem()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsertBulk) SetUpdatedAt(v time.Time) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateUpdatedAt() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
