// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AICallLog is the predicate function for aicalllog builders.
type AICallLog func(*sql.Selector)

// AIUsageDaily is the predicate function for aiusagedaily builders.
type AIUsageDaily func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)

// Snippet is the predicate function for snippet builders.
type Snippet func(*sql.Selector)

// SnippetAIMetadata is the predicate function for snippetaimetadata builders.
type SnippetAIMetadata func(*sql.Selector)

// SnippetLineage is the predicate function for snippetlineage builders.
type SnippetLineage func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)
