app_env: "development"

server:
  port: "8080"

database:
  driver: "postgres"
  source: "" # 机密数据，请在 .env 中设置 DATABASE_SOURCE
  auto_migrate: true

redis:
  addr: "localhost:6379"
  password: "" # 机密数据，请在 .env 中设置 REDIS_PASSWORD
  db: 0

user_platform:
  addr: "localhost:9091" # user-platform gRPC 地址

otel:
  jaeger_endpoint: "localhost:4318"
  service_name: "go-note"
