// Code generated by ent, DO NOT EDIT.

package snippetaimetadata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/go-note/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldOwnerID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldSummary, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldContentHash, v))
}

// PromptVersion applies equality check predicate on the "prompt_version" field. It's identical to PromptVersionEQ.
func PromptVersion(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldPromptVersion, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldModel, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int64) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldOwnerID, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContainsFold(FieldSummary, v))
}

// SuggestedTagsIsNil applies the IsNil predicate on the "suggested_tags" field.
func SuggestedTagsIsNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIsNull(FieldSuggestedTags))
}

// SuggestedTagsNotNil applies the NotNil predicate on the "suggested_tags" field.
func SuggestedTagsNotNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotNull(FieldSuggestedTags))
}

// ExtractedTodosIsNil applies the IsNil predicate on the "extracted_todos" field.
func ExtractedTodosIsNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIsNull(FieldExtractedTodos))
}

// ExtractedTodosNotNil applies the NotNil predicate on the "extracted_todos" field.
func ExtractedTodosNotNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotNull(FieldExtractedTodos))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v uint32) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldContentHash, v))
}

// PromptVersionEQ applies the EQ predicate on the "prompt_version" field.
func PromptVersionEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldPromptVersion, v))
}

// PromptVersionNEQ applies the NEQ predicate on the "prompt_version" field.
func PromptVersionNEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldPromptVersion, v))
}

// PromptVersionIn applies the In predicate on the "prompt_version" field.
func PromptVersionIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldPromptVersion, vs...))
}

// PromptVersionNotIn applies the NotIn predicate on the "prompt_version" field.
func PromptVersionNotIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldPromptVersion, vs...))
}

// PromptVersionGT applies the GT predicate on the "prompt_version" field.
func PromptVersionGT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldPromptVersion, v))
}

// PromptVersionGTE applies the GTE predicate on the "prompt_version" field.
func PromptVersionGTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldPromptVersion, v))
}

// PromptVersionLT applies the LT predicate on the "prompt_version" field.
func PromptVersionLT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldPromptVersion, v))
}

// PromptVersionLTE applies the LTE predicate on the "prompt_version" field.
func PromptVersionLTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldPromptVersion, v))
}

// PromptVersionContains applies the Contains predicate on the "prompt_version" field.
func PromptVersionContains(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContains(FieldPromptVersion, v))
}

// PromptVersionHasPrefix applies the HasPrefix predicate on the "prompt_version" field.
func PromptVersionHasPrefix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasPrefix(FieldPromptVersion, v))
}

// PromptVersionHasSuffix applies the HasSuffix predicate on the "prompt_version" field.
func PromptVersionHasSuffix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasSuffix(FieldPromptVersion, v))
}

// PromptVersionEqualFold applies the EqualFold predicate on the "prompt_version" field.
func PromptVersionEqualFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEqualFold(FieldPromptVersion, v))
}

// PromptVersionContainsFold applies the ContainsFold predicate on the "prompt_version" field.
func PromptVersionContainsFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContainsFold(FieldPromptVersion, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldContainsFold(FieldModel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SnippetAIMetadata) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SnippetAIMetadata) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SnippetAIMetadata) predicate.SnippetAIMetadata {
	return predicate.SnippetAIMetadata(sql.NotPredicates(p))
}
